/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.hoteladmin;

import com.iris.backend.controller.EventController;
import com.iris.backend.controller.WorkRequestController;
import com.iris.backend.model.Event;
import com.iris.backend.model.User;
import com.iris.backend.model.WorkRequest;
import com.iris.ui.HomeJPanel;
import com.iris.ui.HomeLeftJPanel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JSplitPane;

/**
 *
 * @author Snehal
 */
public class HotelAdminScreen extends javax.swing.JPanel {

    /**
     * Creates new form HotelAdminSettings
     */
    
    JSplitPane mainSplitPane;
    WorkRequestController workRequestController;
    EventController eventController;
    
    ArrayList<User> userData;
    
    int hotelAdminId;
     
    public HotelAdminScreen(JSplitPane jSplitPane,  ArrayList<User> userData) throws SQLException {
        initComponents();
        this.mainSplitPane = jSplitPane;
        this.userData = userData;
        workRequestController = new WorkRequestController();
        eventController = new EventController();
        hotelAdminId = userData.get(0).getID();
        populateUserData();
        getNotificationData();
        //Load dashboard (by default)
        try {
            HotelAdminDashboard hotelAdminDashboard = new HotelAdminDashboard(userData);
            jRightSplitPane.setBottomComponent(hotelAdminDashboard);
        } catch (SQLException ex) {
            Logger.getLogger(HotelAdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void getNotificationData() throws SQLException{
        // get notification count
        ArrayList<WorkRequest> wkList = new ArrayList<>(); 
        wkList = workRequestController.getWorkRequestByRoleService(hotelAdminId);
        ArrayList<Event> eventList = eventController.getEventDataByEnterprise(wkList, hotelAdminId);
        int notification = eventList.size();
        notificationBadge.setBadges(notification); 
    }
    
    public void populateUserData() throws SQLException{
//        jUserImageIcon.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/p1.jpg"))); //TODO: get userImage from backend

//System.out.println("PATH - " + this.userData.get(0).getPhoto());
String path = this.userData.get(0).getPhoto().replace("\\", "\\\\");
//System.out.println("PATH - " + path);
ImageIcon icon = new ImageIcon(path);    

jUserImageIcon.setIcon(icon);         

jUserName.setText(userData.get(0).getName());
        // get notification count
        int notification = 10;
        notificationBadge.setBadges(notification); //TODO: get workRequest count for businessAdmin
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaseSplitPane = new javax.swing.JSplitPane();
        jBaseRightPanel = new javax.swing.JPanel();
        jRightSplitPane = new javax.swing.JSplitPane();
        jRightBottomPanel = new javax.swing.JPanel();
        jTopRightPanel = new javax.swing.JPanel();
        jUserImageIcon = new com.iris.ui.resources.ImageAvatar();
        jUserName = new javax.swing.JLabel();
        jUserRole = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        notificationBadge = new com.iris.ui.resources.ButtonBadges();
        messageBadge = new com.iris.ui.resources.ButtonBadges();
        burgerBadge = new com.iris.ui.resources.ButtonBadges();
        jBaseLeftPanel = new javax.swing.JPanel();
        mapleLogo = new com.iris.ui.resources.ImageAvatar();
        jDashboardBtn = new com.iris.ui.resources.Button();
        jRequestsBtn = new com.iris.ui.resources.Button();
        jLogoutBtn = new com.iris.ui.resources.Button();
        jSettingsBtn = new com.iris.ui.resources.Button();

        jBaseSplitPane.setDividerSize(0);

        jRightSplitPane.setDividerSize(0);
        jRightSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jRightBottomPanel.setBackground(new java.awt.Color(245, 241, 241));

        javax.swing.GroupLayout jRightBottomPanelLayout = new javax.swing.GroupLayout(jRightBottomPanel);
        jRightBottomPanel.setLayout(jRightBottomPanelLayout);
        jRightBottomPanelLayout.setHorizontalGroup(
            jRightBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        jRightBottomPanelLayout.setVerticalGroup(
            jRightBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jRightSplitPane.setRightComponent(jRightBottomPanel);

        jTopRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        jTopRightPanel.setMaximumSize(new java.awt.Dimension(985, 80));
        jTopRightPanel.setMinimumSize(new java.awt.Dimension(985, 80));

        jUserName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jUserName.setForeground(new java.awt.Color(127, 127, 127));
        jUserName.setText("User Name");

        jUserRole.setForeground(new java.awt.Color(127, 127, 127));
        jUserRole.setText("Hotel Admin");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        notificationBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/notification.png")));
        notificationBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBadgeActionPerformed(evt);
            }
        });

        messageBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/message.png")));

        burgerBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/menu.png")));
        burgerBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerBadgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTopRightPanelLayout = new javax.swing.GroupLayout(jTopRightPanel);
        jTopRightPanel.setLayout(jTopRightPanelLayout);
        jTopRightPanelLayout.setHorizontalGroup(
            jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopRightPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(burgerBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(620, 620, 620)
                .addComponent(messageBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUserRole, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jUserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jTopRightPanelLayout.setVerticalGroup(
            jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopRightPanelLayout.createSequentialGroup()
                .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUserRole))
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jTopRightPanelLayout.createSequentialGroup()
                .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jUserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notificationBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burgerBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jRightSplitPane.setTopComponent(jTopRightPanel);

        javax.swing.GroupLayout jBaseRightPanelLayout = new javax.swing.GroupLayout(jBaseRightPanel);
        jBaseRightPanel.setLayout(jBaseRightPanelLayout);
        jBaseRightPanelLayout.setHorizontalGroup(
            jBaseRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRightSplitPane)
        );
        jBaseRightPanelLayout.setVerticalGroup(
            jBaseRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRightSplitPane)
        );

        jBaseSplitPane.setRightComponent(jBaseRightPanel);

        jBaseLeftPanel.setBackground(new java.awt.Color(255, 255, 255));

        mapleLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/iris.jpg")));

        jDashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/dash.png")));
        jDashboardBtn.setText("Dashboard");
        jDashboardBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/1.png")));
        jDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDashboardBtnActionPerformed(evt);
            }
        });

        jRequestsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/analytics.png")));
        jRequestsBtn.setText("Requests");
        jRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRequestsBtnActionPerformed(evt);
            }
        });

        jLogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/logout.png")));
        jLogoutBtn.setText("Logout");
        jLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutBtnActionPerformed(evt);
            }
        });

        jSettingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/settings.png")));
        jSettingsBtn.setText("Settings");
        jSettingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSettingsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBaseLeftPanelLayout = new javax.swing.GroupLayout(jBaseLeftPanel);
        jBaseLeftPanel.setLayout(jBaseLeftPanelLayout);
        jBaseLeftPanelLayout.setHorizontalGroup(
            jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBaseLeftPanelLayout.setVerticalGroup(
            jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSettingsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(jLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );

        jBaseSplitPane.setLeftComponent(jBaseLeftPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseSplitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void notificationBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBadgeActionPerformed
       
    }//GEN-LAST:event_notificationBadgeActionPerformed

    private void burgerBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerBadgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_burgerBadgeActionPerformed

    private void jDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDashboardBtnActionPerformed
        try {
            getNotificationData();
            HotelAdminDashboard hotelAdminDashboard = new HotelAdminDashboard(userData);
            jRightSplitPane.setBottomComponent(hotelAdminDashboard);
        } catch (SQLException ex) {
            Logger.getLogger(HotelAdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDashboardBtnActionPerformed

    private void jRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRequestsBtnActionPerformed
        try {
            getNotificationData();
            HotelAdminRequest hotelAdminRequest = new HotelAdminRequest(userData);
            jRightSplitPane.setBottomComponent(hotelAdminRequest);
        } catch (SQLException ex) {
            Logger.getLogger(HotelAdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRequestsBtnActionPerformed

    private void jLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutBtnActionPerformed
        //Reset right panel
        HomeJPanel homeScreen = new HomeJPanel(this.mainSplitPane);
        this.mainSplitPane.setRightComponent(homeScreen);
        //Reset left panel
        HomeLeftJPanel homeLeftPanel = new HomeLeftJPanel(this.mainSplitPane);
        this.mainSplitPane.setLeftComponent(homeLeftPanel);
    }//GEN-LAST:event_jLogoutBtnActionPerformed

    private void jSettingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSettingsBtnActionPerformed
        try {
            getNotificationData();
            HotelAdminSettings hotelAdminSettings = new HotelAdminSettings(userData);
            jRightSplitPane.setBottomComponent(hotelAdminSettings);
        } catch (SQLException ex) {
            Logger.getLogger(HotelAdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSettingsBtnActionPerformed

    public JSplitPane getBaseSplitPane(){
        return this.jBaseSplitPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.ButtonBadges burgerBadge;
    private javax.swing.JPanel jBaseLeftPanel;
    private javax.swing.JPanel jBaseRightPanel;
    private javax.swing.JSplitPane jBaseSplitPane;
    private com.iris.ui.resources.Button jDashboardBtn;
    private com.iris.ui.resources.Button jLogoutBtn;
    private com.iris.ui.resources.Button jRequestsBtn;
    private javax.swing.JPanel jRightBottomPanel;
    private javax.swing.JSplitPane jRightSplitPane;
    private javax.swing.JSeparator jSeparator1;
    private com.iris.ui.resources.Button jSettingsBtn;
    private javax.swing.JPanel jTopRightPanel;
    private com.iris.ui.resources.ImageAvatar jUserImageIcon;
    private javax.swing.JLabel jUserName;
    private javax.swing.JLabel jUserRole;
    private com.iris.ui.resources.ImageAvatar mapleLogo;
    private com.iris.ui.resources.ButtonBadges messageBadge;
    private com.iris.ui.resources.ButtonBadges notificationBadge;
    // End of variables declaration//GEN-END:variables
}
