/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.hoteladmin;

import com.iris.backend.controller.EnterpriseController;
import com.iris.backend.model.Hotel;
import com.iris.backend.model.User;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Snehal
 */
public class HotelAdminDashboard extends javax.swing.JPanel {

    /**
     * Creates new form HotelAdminDashboard
     */
    
    ArrayList<User> userData;
    
    EnterpriseController enterpriseController;
    
    public HotelAdminDashboard(ArrayList<User> userData) throws SQLException {
        initComponents();
        this.userData = userData;
        enterpriseController = new EnterpriseController();
        
        
        populateHotelData();
        disableFields();

    }
    
    private void populateHotelData() throws SQLException{

        ResultSet resultSet = enterpriseController.getEnterpriseData("HOTEL", userData.get(0).getID());        
        Hotel hotelData = hotelMapper(resultSet);

//        jHotelPhoto.setIcon(icon);
        jHotelName.setText(hotelData.getHotelName());
        jHotelAddress.setText(hotelData.getHotelAddress());
        jHotelArea.setText(hotelData.getHotelArea());
        jHotelCapacity.setText(hotelData.getCapacity());
        jHotelType.setText(hotelData.getHotelType());
        jHotelEmail.setText(hotelData.getEmail());  
        jHotelPhone.setText(hotelData.getPhone());
        String path = hotelData.getPhoto().replace("\\", "\\\\");
        ImageIcon icon = new ImageIcon(path);    
                jHotelPhoto.setIcon(icon);
    }
    
    private void disableFields(){
        jHotelName.setEnabled(false);
        jHotelAddress.setEnabled(false);
        jHotelArea.setEnabled(false);
        jHotelCapacity.setEnabled(false);
        jHotelType.setEnabled(false);
        jHotelEmail.setEnabled(false);
        jHotelPhone.setEnabled(false);
    }
    
    private Hotel hotelMapper(ResultSet resultSet) throws SQLException{
        Hotel hotel = new Hotel();
        while(resultSet.next()){
            hotel.setHotelID(Integer.parseInt(resultSet.getString("H_ID")));
            hotel.setHotelName(resultSet.getString("H_NAME"));
            hotel.setHotelAddress(resultSet.getString("H_ADDRESS"));
            hotel.setHotelArea(resultSet.getString("H_AREA"));
            hotel.setHotelType(resultSet.getString("H_TYPE"));
            hotel.setCapacity(resultSet.getString("H_CAPACITY"));
            hotel.setHotelAdmin(resultSet.getString("H_ADMIN_ID"));
            hotel.setBookedDates(resultSet.getString("H_BOOKED_DATES"));
            hotel.setPhoto(resultSet.getString("H_PHOTO"));
            hotel.setEmail(resultSet.getString("H_EMAIL"));
            hotel.setPhone(resultSet.getString("H_PHONE"));
//        hotel.setStatus(resultSet.getString("H_STATUS"));
        }
        
        return hotel; 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRoute = new javax.swing.JLabel();
        jHotelPhoto = new com.iris.ui.resources.ImageAvatar();
        jHotelName = new com.iris.ui.resources.TextField();
        jHotelAddress = new com.iris.ui.resources.TextField();
        jHotelArea = new com.iris.ui.resources.TextField();
        jHotelCapacity = new com.iris.ui.resources.TextField();
        jHotelType = new com.iris.ui.resources.TextField();
        jHotelEmail = new com.iris.ui.resources.TextField();
        jHotelPhone = new com.iris.ui.resources.TextField();

        setBackground(new java.awt.Color(245, 241, 241));

        jRoute.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRoute.setForeground(new java.awt.Color(4, 72, 210));
        jRoute.setText("Admin / Dashboard");

        jHotelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/hotel.png")));

        jHotelName.setLabelText("Hotel Name");
        jHotelName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHotelNameActionPerformed(evt);
            }
        });

        jHotelAddress.setLabelText("Address");

        jHotelArea.setLabelText("Area");

        jHotelCapacity.setLabelText("Capacity");

        jHotelType.setLabelText("Hotel Type");

        jHotelEmail.setLabelText("Email");

        jHotelPhone.setLabelText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHotelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHotelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jHotelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jHotelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jHotelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHotelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jHotelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jRoute))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jHotelAddress, jHotelArea, jHotelCapacity, jHotelEmail, jHotelName, jHotelPhone, jHotelType});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jRoute)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHotelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHotelArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHotelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHotelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jHotelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHotelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jHotelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jHotelNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHotelNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHotelNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.TextField jHotelAddress;
    private com.iris.ui.resources.TextField jHotelArea;
    private com.iris.ui.resources.TextField jHotelCapacity;
    private com.iris.ui.resources.TextField jHotelEmail;
    private com.iris.ui.resources.TextField jHotelName;
    private com.iris.ui.resources.TextField jHotelPhone;
    private com.iris.ui.resources.ImageAvatar jHotelPhoto;
    private com.iris.ui.resources.TextField jHotelType;
    private javax.swing.JLabel jRoute;
    // End of variables declaration//GEN-END:variables
}
