/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.usermgmt;

import com.iris.backend.controller.EnterpriseController;
import com.iris.backend.controller.EventController;
import com.iris.backend.controller.UserController;
import com.iris.backend.controller.WorkRequestController;
import com.iris.backend.model.Event;
import com.iris.backend.model.User;
import com.iris.backend.model.WorkRequest;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Snehal
 */
public class UserEventsList extends javax.swing.JPanel {

    /**
     * Creates new form HotelAdminRequest
     */
    JSplitPane mainSplitPane;
    EventController eventController;
    EnterpriseController enterpriseController;
    WorkRequestController wrController;
    UserController userController;
    User loggedInUser;
    int customerID = 0;

    public UserEventsList(JSplitPane jSplitPane, User loggedUser) throws SQLException {
        initComponents();
        this.mainSplitPane = jSplitPane;
        this.loggedInUser = loggedUser;
        eventController = new EventController();
        wrController = new WorkRequestController();
        userController = new UserController();
        enterpriseController = new EnterpriseController();
        customerID = this.loggedInUser.getID();
        table.fixTable(jScrollPane2);
        populateTableData();
    }

    //Table Data
    private void populateTableData() throws SQLException {
        DefaultTableModel dtmodel = (DefaultTableModel) table.getModel();
        dtmodel.setRowCount(0);
        ArrayList<Event> eventList = eventController.getCustomerEventList(customerID);
        for (Event evt : eventList) {
            Object[] obj = new Object[10];
            obj[0] = evt.getEventName();
            obj[1] = evt.getEventDescription();
            obj[2] = evt.getEventType();
            obj[3] = evt.getAccomodationCount();
            obj[4] = evt.getFunctionHallCount();
            obj[5] = evt.getCateringCount();
            obj[6] = evt.getTravelCount();
            obj[7] = evt.getEventFrom();
            obj[8] = evt.getEventTo();
            obj[9] = evt.getStatus();
            dtmodel.addRow(obj);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRoute = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new com.iris.ui.resources.Table();
        jRefreshTableBtn = new com.iris.ui.resources.ButtonBadges();

        setBackground(new java.awt.Color(245, 241, 241));

        jRoute.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRoute.setForeground(new java.awt.Color(4, 72, 210));
        jRoute.setText("Customer / Events");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Event Description", "Event Type",
                "Accomodation", "Function Hall",
                "Catering", "Travel",
                "Event From", "Event To","Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jRefreshTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/refresh.png")));
        jRefreshTableBtn.setMaximumSize(new java.awt.Dimension(20, 20));
        jRefreshTableBtn.setMinimumSize(new java.awt.Dimension(20, 20));
        jRefreshTableBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        jRefreshTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshTableBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRefreshTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRoute)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jRoute)
                .addGap(25, 25, 25)
                .addComponent(jRefreshTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked

    private void jRefreshTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshTableBtnActionPerformed

        try {
            populateTableData();
        } catch (SQLException ex) {
        }

    }//GEN-LAST:event_jRefreshTableBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.ButtonBadges jRefreshTableBtn;
    private javax.swing.JLabel jRoute;
    private javax.swing.JScrollPane jScrollPane2;
    private com.iris.ui.resources.Table table;
    // End of variables declaration//GEN-END:variables
}
