/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.businessadmin;

import com.iris.backend.controller.WorkRequestController;
import com.iris.backend.model.User;
import com.iris.ui.resources.ModelPieChart;
import com.iris.ui.resources.PieChart;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author harsh
 */
public class BusinessAdminAnalytics extends javax.swing.JPanel {

    /**
     * Creates new form BusinessAdminAnalytics
     */
    
    WorkRequestController workRequestController;
    ArrayList<User> userData;
    int businessAdminId;
    
    public BusinessAdminAnalytics(ArrayList<User> userData) throws SQLException {
        initComponents();
        workRequestController = new WorkRequestController();
        this.userData = userData;
        businessAdminId = userData.get(0).getID();
        populateChartData();
    }
    
    private void populateChartData() throws SQLException{
        
        PieChart pieChart=new PieChart();

        //Load Hotel Charts
        hotelChart.setChartType(PieChart.PeiChartType.DONUT_CHART);
        int approvedHotel = workRequestController.getHotelEnterpriseData(businessAdminId, "ACCEPTED").size();
        int rejectedHotel = workRequestController.getHotelEnterpriseData(businessAdminId, "REJECTED").size();
        int pendingHotel = workRequestController.getHotelEnterpriseData(businessAdminId, "PENDING").size();
        if(approvedHotel!=0){
            hotelChart.addData(new ModelPieChart("APPROVED", approvedHotel, new Color(47, 157, 64)));
        }
        if(rejectedHotel!=0){
            hotelChart.addData(new ModelPieChart("REJECTED", rejectedHotel, new Color(221, 65, 65)));
        }
        if(pendingHotel!=0){
            hotelChart.addData(new ModelPieChart("PENDING", pendingHotel, new Color(196, 151, 58)));
        }
 
        //Load Catering Charts
        cateringChart.setChartType(PieChart.PeiChartType.DONUT_CHART);
        int approvedCatering = workRequestController.getCateringEnterpriseData(businessAdminId, "ACCEPTED").size();
        int rejectedCatering = workRequestController.getCateringEnterpriseData(businessAdminId, "REJECTED").size();
        int pendingCatering = workRequestController.getCateringEnterpriseData(businessAdminId, "PENDING").size();
        if(approvedCatering!=0){
            cateringChart.addData(new ModelPieChart("APPROVED", approvedCatering, new Color(47, 157, 64)));
        }
        if(rejectedCatering!=0){
            cateringChart.addData(new ModelPieChart("REJECTED", rejectedCatering, new Color(221, 65, 65)));
        }
        if(pendingCatering!=0){
            cateringChart.addData(new ModelPieChart("PENDING", pendingCatering, new Color(196, 151, 58)));
        }
        
        //Load TravelAgent Charts
        travelChart.setChartType(PieChart.PeiChartType.DONUT_CHART);
        int approvedTravel = workRequestController.getTravelAgentEnterpriseData(businessAdminId, "ACCEPTED").size();
        int rejectedTravel = workRequestController.getTravelAgentEnterpriseData(businessAdminId, "REJECTED").size();
        int pendingTravel = workRequestController.getTravelAgentEnterpriseData(businessAdminId, "PENDING").size();
        if(approvedTravel!=0){
            travelChart.addData(new ModelPieChart("APPROVED", approvedTravel, new Color(47, 157, 64)));
        }
        if(rejectedTravel!=0){
            travelChart.addData(new ModelPieChart("REJECTED", rejectedTravel, new Color(221, 65, 65)));
        }
        if(pendingTravel!=0){
            travelChart.addData(new ModelPieChart("PENDING", pendingTravel, new Color(196, 151, 58)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRoute = new javax.swing.JLabel();
        hotelChart = new com.iris.ui.resources.PieChart();
        cateringChart = new com.iris.ui.resources.PieChart();
        travelChart = new com.iris.ui.resources.PieChart();
        imageAvatar1 = new com.iris.ui.resources.ImageAvatar();
        imageAvatar2 = new com.iris.ui.resources.ImageAvatar();
        imageAvatar3 = new com.iris.ui.resources.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 241, 241));

        jRoute.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRoute.setForeground(new java.awt.Color(4, 72, 210));
        jRoute.setText("Admin / Analytics");

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/hotel.png")));

        imageAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/catering.png")));

        imageAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/travelAgent.png")));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("HOTEL");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("CATERING");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("TRAVEL AGENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hotelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cateringChart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(travelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRoute)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234)
                                .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel3)))))
                .addContainerGap(717, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jRoute)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cateringChart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(travelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.PieChart cateringChart;
    private com.iris.ui.resources.PieChart hotelChart;
    private com.iris.ui.resources.ImageAvatar imageAvatar1;
    private com.iris.ui.resources.ImageAvatar imageAvatar2;
    private com.iris.ui.resources.ImageAvatar imageAvatar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jRoute;
    private com.iris.ui.resources.PieChart travelChart;
    // End of variables declaration//GEN-END:variables
}
