/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.cateringadmin;

import com.iris.backend.controller.UserController;
import com.iris.backend.model.User;
import java.awt.Cursor;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Aayuka Nirawade
 */
public class CateringAdminSettings extends javax.swing.JPanel {

    /**
     * Creates new form HotelAdminSettings
     */
    ArrayList<User> userData;
    
    UserController userController;

    public CateringAdminSettings(ArrayList<User> userData) throws SQLException {
        initComponents();
        this.userData = userData;
        userController = new UserController();
        String path = this.userData.get(0).getPhoto().replace("\\", "\\\\");
        jUserPhoto.setIcon(new ImageIcon(path));
        jName.setText(userData.get(0).getName());
        jName.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRoute = new javax.swing.JLabel();
        jUserPhoto = new com.iris.ui.resources.ImageAvatar();
        jName = new com.iris.ui.resources.TextField();
        jNewPasswordField = new com.iris.ui.resources.PasswordField();
        jSaveBtn = new com.iris.ui.resources.ButtonBadges();
        jClearBtn = new com.iris.ui.resources.ButtonBadges();
        jConfirmPasswordField = new com.iris.ui.resources.PasswordField();
        jOldPasswordField = new com.iris.ui.resources.PasswordField();

        setBackground(new java.awt.Color(245, 241, 241));

        jRoute.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jRoute.setForeground(new java.awt.Color(4, 72, 210));
        jRoute.setText("Admin / Settings");

        jUserPhoto.setBackground(new java.awt.Color(255, 255, 255));
        jUserPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUserPhotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jUserPhotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUserPhotoMouseExited(evt);
            }
        });

        jName.setLabelText("");

        jNewPasswordField.setLabelText("New Password");

        jSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/tick.png")));
        jSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBtnActionPerformed(evt);
            }
        });

        jClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/cross.png")));
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBtnActionPerformed(evt);
            }
        });

        jConfirmPasswordField.setLabelText("Confirm Password");
        jConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmPasswordFieldActionPerformed(evt);
            }
        });

        jOldPasswordField.setLabelText("Old Password");
        jOldPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jOldPasswordFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jRoute))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jOldPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(447, 447, 447)
                                .addComponent(jSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jRoute)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(377, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUserPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserPhotoMouseClicked

        //Upload image
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        if(file == null){ // If no image is selected
            //show validation
            return;
        }
        String filename = file.getAbsolutePath();
        ImageIcon icon = new ImageIcon(filename);
        jUserPhoto.setIcon(icon);

    }//GEN-LAST:event_jUserPhotoMouseClicked

    private void jUserPhotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserPhotoMouseEntered

        //Change Cursor
        jUserPhoto.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jUserPhoto.setBorderSize(2);

    }//GEN-LAST:event_jUserPhotoMouseEntered

    private void jUserPhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserPhotoMouseExited
        // TODO add your handling code here:
        jUserPhoto.setBorderSize(0);
    }//GEN-LAST:event_jUserPhotoMouseExited

    private void jSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBtnActionPerformed

        try {
            //Validate Old Password
            String oldPassword = new String(jOldPasswordField.getPassword());
            String newPassword = new String(jNewPasswordField.getPassword());
            String confirmPassword = new String(jConfirmPasswordField.getPassword());
            int isValid = userController.updateUserPassword(userData, oldPassword, newPassword, confirmPassword);
            if(isValid==-1){
                JOptionPane.showMessageDialog(null, "Password mismatch");
                return;
            } else if(isValid==-2){
                JOptionPane.showMessageDialog(null, "Incorrect Old Password");
                return;
            } else if(isValid==-3){
                JOptionPane.showMessageDialog(null, "Fields cannot be empty");
                return;
            }
            JOptionPane.showMessageDialog(null, "Password updated!");
            jOldPasswordField.setText("");
            jNewPasswordField.setText("");
            jConfirmPasswordField.setText("");

        } catch (SQLException ex) {
            
        }

    }//GEN-LAST:event_jSaveBtnActionPerformed

    private void jClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBtnActionPerformed
        jOldPasswordField.setText("");
        jNewPasswordField.setText("");
        jConfirmPasswordField.setText("");
    }//GEN-LAST:event_jClearBtnActionPerformed

    private void jConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConfirmPasswordFieldActionPerformed

    private void jOldPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOldPasswordFieldKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jOldPasswordFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.ButtonBadges jClearBtn;
    private com.iris.ui.resources.PasswordField jConfirmPasswordField;
    private com.iris.ui.resources.TextField jName;
    private com.iris.ui.resources.PasswordField jNewPasswordField;
    private com.iris.ui.resources.PasswordField jOldPasswordField;
    private javax.swing.JLabel jRoute;
    private com.iris.ui.resources.ButtonBadges jSaveBtn;
    private com.iris.ui.resources.ImageAvatar jUserPhoto;
    // End of variables declaration//GEN-END:variables
}
