/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.admin;

import elearning.models.UserDefaultDataModel;
import elearning.models.UserModel;
import elearning.models.UserSignUpModel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harsh
 */
public class AdminDashboardPanel extends javax.swing.JPanel {

    JPanel appContainerPanel;
    UserSignUpModel userSignUpObj;
    UserModel userObj;
    UserDefaultDataModel userDefaultDataObj;

    /**
     * Creates new form AdminDashboardPanel
     *
     * @param appContainerPanel
     * @param userSignUpObj
     * @param userObj
     * @param userDefaultDataObj
     */
    public AdminDashboardPanel(JPanel appContainerPanel,
            UserSignUpModel userSignUpObj, UserModel userObj,
            UserDefaultDataModel userDefaultDataObj) {
        initComponents();
        this.appContainerPanel = appContainerPanel;
        this.userSignUpObj = userSignUpObj;
        this.userObj = userObj;
        this.userDefaultDataObj = userDefaultDataObj;

        System.out.println("User Details Size : " + this.userSignUpObj.getUserLi().size());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        adminDashMenuPanel = new javax.swing.JPanel();
        adminDashCourseCatalogButton = new javax.swing.JButton();
        adminDashProfessorsButton = new javax.swing.JButton();
        adminDashStudentsButton = new javax.swing.JButton();
        adminDashProfileButton = new javax.swing.JButton();
        ApproveCertsButton = new javax.swing.JButton();
        adminDashContentPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        adminDashMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminDashMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adminDashCourseCatalogButton.setBackground(new java.awt.Color(51, 153, 255));
        adminDashCourseCatalogButton.setText("Course Catalog");
        adminDashCourseCatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDashCourseCatalogButtonActionPerformed(evt);
            }
        });

        adminDashProfessorsButton.setBackground(new java.awt.Color(51, 153, 255));
        adminDashProfessorsButton.setText("Professors");
        adminDashProfessorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDashProfessorsButtonActionPerformed(evt);
            }
        });

        adminDashStudentsButton.setBackground(new java.awt.Color(51, 153, 255));
        adminDashStudentsButton.setText("Students");
        adminDashStudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDashStudentsButtonActionPerformed(evt);
            }
        });

        adminDashProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        adminDashProfileButton.setText("Profile");
        adminDashProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDashProfileButtonActionPerformed(evt);
            }
        });

        ApproveCertsButton.setBackground(new java.awt.Color(51, 153, 255));
        ApproveCertsButton.setText("Approve Users");
        ApproveCertsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveCertsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminDashMenuPanelLayout = new javax.swing.GroupLayout(adminDashMenuPanel);
        adminDashMenuPanel.setLayout(adminDashMenuPanelLayout);
        adminDashMenuPanelLayout.setHorizontalGroup(
            adminDashMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminDashCourseCatalogButton)
                .addGap(18, 18, 18)
                .addComponent(adminDashProfessorsButton)
                .addGap(18, 18, 18)
                .addComponent(adminDashStudentsButton)
                .addGap(18, 18, 18)
                .addComponent(ApproveCertsButton)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminDashProfileButton)
                .addContainerGap())
        );
        adminDashMenuPanelLayout.setVerticalGroup(
            adminDashMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminDashProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(adminDashMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDashCourseCatalogButton)
                    .addComponent(adminDashProfessorsButton)
                    .addComponent(adminDashStudentsButton)
                    .addComponent(ApproveCertsButton))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(adminDashMenuPanel);

        adminDashContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        adminDashContentPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(adminDashContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminDashCourseCatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashCourseCatalogButtonActionPerformed
        // TODO add your handling code here:
        AdminCourseCatalogPanel courseCatalog = new AdminCourseCatalogPanel(
                adminDashContentPanel, this.userDefaultDataObj);
        adminDashContentPanel.add("AdminCourseCatalog", courseCatalog);
        CardLayout layout = (CardLayout) adminDashContentPanel.getLayout();
        layout.next(adminDashContentPanel);
    }//GEN-LAST:event_adminDashCourseCatalogButtonActionPerformed

    private void adminDashProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashProfileButtonActionPerformed
        // TODO add your handling code here:
        AdminProfileResetPanel adminProfile = new AdminProfileResetPanel(appContainerPanel,
                adminDashContentPanel, userObj, this.userSignUpObj);
        adminDashContentPanel.add("AdminProfile", adminProfile);
        CardLayout layout = (CardLayout) adminDashContentPanel.getLayout();
        layout.next(adminDashContentPanel);
    }//GEN-LAST:event_adminDashProfileButtonActionPerformed

    private void adminDashStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashStudentsButtonActionPerformed
        // TODO add your handling code here:
        AdminRegisteredStudentsPanel adminStudents = new AdminRegisteredStudentsPanel(
                adminDashContentPanel, userSignUpObj);
        adminDashContentPanel.add("AdminStudents", adminStudents);
        CardLayout layout = (CardLayout) adminDashContentPanel.getLayout();
        layout.next(adminDashContentPanel);

    }//GEN-LAST:event_adminDashStudentsButtonActionPerformed

    private void adminDashProfessorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashProfessorsButtonActionPerformed
        // TODO add your handling code here:
        AdminRegisteredProfessorsPanel adminProfessors = new AdminRegisteredProfessorsPanel(
                adminDashContentPanel, userSignUpObj);
        adminDashContentPanel.add("AdminProfessors", adminProfessors);
        CardLayout layout = (CardLayout) adminDashContentPanel.getLayout();
        layout.next(adminDashContentPanel);
    }//GEN-LAST:event_adminDashProfessorsButtonActionPerformed

    private void ApproveCertsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveCertsButtonActionPerformed
        // TODO add your handling code here:
        AdminApproveUsersPanel appoveUserPanel = new AdminApproveUsersPanel(
                adminDashContentPanel, userSignUpObj);
        adminDashContentPanel.add("AdminApprovals", appoveUserPanel);
        CardLayout layout = (CardLayout) adminDashContentPanel.getLayout();
        layout.next(adminDashContentPanel);
    }//GEN-LAST:event_ApproveCertsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveCertsButton;
    private javax.swing.JPanel adminDashContentPanel;
    private javax.swing.JButton adminDashCourseCatalogButton;
    private javax.swing.JPanel adminDashMenuPanel;
    private javax.swing.JButton adminDashProfessorsButton;
    private javax.swing.JButton adminDashProfileButton;
    private javax.swing.JButton adminDashStudentsButton;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
