/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.hradmin;

import com.iris.backend.controller.UserController;
import java.awt.Cursor;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author harsh
 */
public class HRAdminManageScreen extends javax.swing.JPanel {

    /**
     * Creates new form HRAdminManageScreen
     */
    UserController userController;
    
    String path;
    
    public HRAdminManageScreen() throws SQLException {
        initComponents();
        userController = new UserController();
        jUserPhoto.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/user.png"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocation = new javax.swing.JLabel();
        jName = new com.iris.ui.resources.TextField();
        jUserPhoto = new com.iris.ui.resources.ImageAvatar();
        jEmail = new com.iris.ui.resources.TextField();
        jUserName = new com.iris.ui.resources.TextField();
        jPhone = new com.iris.ui.resources.TextField();
        jPostalCode = new com.iris.ui.resources.TextField();
        jSaveBtn = new com.iris.ui.resources.ButtonBadges();
        jClearBtn = new com.iris.ui.resources.ButtonBadges();
        jRole = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(245, 241, 241));

        jLocation.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLocation.setForeground(new java.awt.Color(4, 72, 210));
        jLocation.setText("Admin / Manage");

        jName.setLabelText("Name");

        jUserPhoto.setBackground(new java.awt.Color(255, 255, 255));
        jUserPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUserPhotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jUserPhotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUserPhotoMouseExited(evt);
            }
        });

        jEmail.setLabelText("Email");

        jUserName.setLabelText("Username");

        jPhone.setLabelText("Contact Number");

        jPostalCode.setLabelText("Postal Code");

        jSaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/tick.png")));
        jSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBtnActionPerformed(evt);
            }
        });

        jClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/cross.png")));
        jClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBtnActionPerformed(evt);
            }
        });

        jRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Event Admin", "Business Admin", "Event Manager" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLocation)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPostalCode, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLocation)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(351, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUserPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserPhotoMouseClicked

        //Upload image
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        if(file == null){ // If no image is selected
            //show validation
            return;
        }
        String filename = file.getAbsolutePath();
        this.path = filename;
        ImageIcon icon = new ImageIcon(filename);
        jUserPhoto.setIcon(icon);

    }//GEN-LAST:event_jUserPhotoMouseClicked

    private void jUserPhotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserPhotoMouseEntered

        //Change Cursor
        jUserPhoto.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jUserPhoto.setBorderSize(2);

    }//GEN-LAST:event_jUserPhotoMouseEntered

    private void jUserPhotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserPhotoMouseExited
        // TODO add your handling code here:
        jUserPhoto.setBorderSize(0);
    }//GEN-LAST:event_jUserPhotoMouseExited

    private void jSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBtnActionPerformed
        try {
            String name = jName.getText();
            String userName = jUserName.getText();
            String email = jEmail.getText();
            String phoneNumber = jPhone.getText();
            String postalCode = jPostalCode.getText();
            String role = jRole.getSelectedItem().toString();
            String filePath = this.path;
            int ID = userController.getAllUsers();
            if(name.equalsIgnoreCase("") || userName.equalsIgnoreCase("") || 
                    email.equalsIgnoreCase("") || phoneNumber.equalsIgnoreCase("") ||
                    postalCode.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(null, "Fields cannot be empty");
                return;
            }
            userController.insertUserDataController(ID, role, name, email, phoneNumber, 
                    userName, userName, filePath, postalCode, "ACCEPTED");
            
            jName.setText("");
            jEmail.setText("");
            jPhone.setText("");
            jPostalCode.setText("");
            jUserName.setText("");
            jUserPhoto.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/user.png"))); 
            
        } catch (SQLException ex) {
            Logger.getLogger(HRAdminManageScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

            

    }//GEN-LAST:event_jSaveBtnActionPerformed

    private void jClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearBtnActionPerformed
        jName.setText("");
        jEmail.setText("");
        jPhone.setText("");
        jPostalCode.setText("");
        jUserName.setText("");
        jUserPhoto.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/user.png"))); 
    }//GEN-LAST:event_jClearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.ButtonBadges jClearBtn;
    private com.iris.ui.resources.TextField jEmail;
    private javax.swing.JLabel jLocation;
    private com.iris.ui.resources.TextField jName;
    private com.iris.ui.resources.TextField jPhone;
    private com.iris.ui.resources.TextField jPostalCode;
    private javax.swing.JComboBox<String> jRole;
    private com.iris.ui.resources.ButtonBadges jSaveBtn;
    private com.iris.ui.resources.TextField jUserName;
    private com.iris.ui.resources.ImageAvatar jUserPhoto;
    // End of variables declaration//GEN-END:variables
}
