/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.hradmin;

import com.iris.backend.controller.EventController;
import com.iris.backend.controller.UserController;
import com.iris.backend.controller.WorkRequestController;
import com.iris.backend.model.Event;
import com.iris.backend.model.User;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harsh
 */

public class HRAdminDashboard extends javax.swing.JPanel {
    
    WorkRequestController workRequestController;
    UserController userController;
    ArrayList<User> userData;
    
    int hrAdminId;
    int adminClick = 0;
    int managerClick = 0;
    
    public HRAdminDashboard(ArrayList<User> userData) throws SQLException {
        initComponents();
        workRequestController = new WorkRequestController();
        userController = new UserController();
        this.userData = userData;
        hrAdminId = userData.get(0).getID();
        populateCardData();
        populateTableData("ALL");
        table.fixTable(jScrollPane1); //apply table theme
    }
    
    //Table Data
    private void populateTableData(String type) throws SQLException {
        
        DefaultTableModel dtmodel = (DefaultTableModel) table.getModel();
        dtmodel.setRowCount(0);
        ArrayList<User> eventList = new ArrayList<>(); 
        ArrayList<User> publicEventList = new ArrayList<>();
        ArrayList<User> privateEventList = new ArrayList<>();
           
        if(type.equalsIgnoreCase("ADMIN")){
            publicEventList = userController.getMapleAdminData();
            for(User evt: publicEventList){
                Object[] obj = new Object[5];
                obj[0] = evt.getName();
                obj[1] = evt.getRole();
                obj[2] = evt.getEmail();
                obj[3] = evt.getPhoneNum();
                obj[4] = evt.getPostalCode();
                dtmodel.addRow(obj);
            }
        } else if(type.equalsIgnoreCase("EVENT MANAGER")){
            privateEventList = userController.getMapleManagerData();
            for(User evt: privateEventList){
                Object[] obj = new Object[5];
                obj[0] = evt.getName();
                obj[1] = evt.getRole();
                obj[2] = evt.getEmail();
                obj[3] = evt.getPhoneNum();
                obj[4] = evt.getPostalCode();
                dtmodel.addRow(obj);
            }
        } else{ 
             publicEventList = userController.getMapleAdminData();
            for(User evt: publicEventList){
                Object[] obj = new Object[5];
                obj[0] = evt.getName();
                obj[1] = evt.getRole();
                obj[2] = evt.getEmail();
                obj[3] = evt.getPhoneNum();
                obj[4] = evt.getPostalCode();
                dtmodel.addRow(obj);
            }
            privateEventList = userController.getMapleManagerData();
            for(User evt: privateEventList){
                Object[] obj = new Object[5];
                obj[0] = evt.getName();
                obj[1] = evt.getRole();
                obj[2] = evt.getEmail();
                obj[3] = evt.getPhoneNum();
                obj[4] = evt.getPostalCode();
                dtmodel.addRow(obj);
            }
        }
    }
    
    //Card Data
    private void populateCardData() throws SQLException{
        
        //Load Icons
        jMapleManagers.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/manager.png")));
        jMapleAdmins.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/admin.png")));
          
        //Set Description
        jMapleManagers.setDescription("Event Managers");
        jMapleAdmins.setDescription("Maple Admins");
        
        //Assign Request Values
        jMapleManagers.setValues("# " + userController.getMapleManagerData().size());
        jMapleAdmins.setValues("# " + userController.getMapleAdminData().size());
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMapleManagers = new com.iris.ui.resources.Card();
        jTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new com.iris.ui.resources.Table();
        jLocation = new javax.swing.JLabel();
        jRefreshTableBtn = new com.iris.ui.resources.ButtonBadges();
        jMapleAdmins = new com.iris.ui.resources.Card();

        setBackground(new java.awt.Color(245, 241, 241));
        setMaximumSize(new java.awt.Dimension(1196, 720));
        setMinimumSize(new java.awt.Dimension(1196, 720));
        setPreferredSize(new java.awt.Dimension(1196, 720));
        setRequestFocusEnabled(false);

        jMapleManagers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMapleManagersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMapleManagersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMapleManagersMouseExited(evt);
            }
        });

        jTablePanel.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Role", "Email", "Contact Info", "Postal Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jTablePanelLayout = new javax.swing.GroupLayout(jTablePanel);
        jTablePanel.setLayout(jTablePanelLayout);
        jTablePanelLayout.setHorizontalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        jTablePanelLayout.setVerticalGroup(
            jTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLocation.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLocation.setForeground(new java.awt.Color(4, 72, 210));
        jLocation.setText("HR Admin / Dashboard");

        jRefreshTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/refresh.png")));
        jRefreshTableBtn.setMaximumSize(new java.awt.Dimension(20, 20));
        jRefreshTableBtn.setMinimumSize(new java.awt.Dimension(20, 20));
        jRefreshTableBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        jRefreshTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshTableBtnActionPerformed(evt);
            }
        });

        jMapleAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMapleAdminsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMapleAdminsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMapleAdminsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLocation)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRefreshTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jMapleManagers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jMapleAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(894, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLocation)
                .addGap(30, 30, 30)
                .addComponent(jMapleManagers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jRefreshTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jMapleAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(509, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRefreshTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshTableBtnActionPerformed
        try { 
            populateTableData("ALL");
            
            //Reset card colors
            jMapleManagers.setBackground(Color.white);
            jMapleAdmins.setBackground(Color.white);
            //Reset card click counter
            adminClick = 0;
            managerClick = 0;
            populateCardData();
        } catch (SQLException ex) {
            Logger.getLogger(HRAdminDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jRefreshTableBtnActionPerformed

    private void jMapleManagersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapleManagersMouseClicked
        //Apply CSS
        jMapleManagers.setBackground(Color.CYAN);
        jMapleAdmins.setBackground(Color.white);
        
        try {
            //Refresh Table Data
            populateTableData("EVENT MANAGER");
        } catch (SQLException ex) {
            
        }
        
        adminClick = 0;
        managerClick = 1;
    }//GEN-LAST:event_jMapleManagersMouseClicked

    private void jMapleManagersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapleManagersMouseEntered
        // TODO add your handling code here:
        jMapleManagers.setBackground(Color.CYAN);
    }//GEN-LAST:event_jMapleManagersMouseEntered

    private void jMapleManagersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapleManagersMouseExited
        // TODO add your handling code here:
        if(managerClick==1 && adminClick==0){
            jMapleManagers.setBackground(Color.CYAN);
            return;
        }
            jMapleManagers.setBackground(Color.white);
            managerClick = 0;
    }//GEN-LAST:event_jMapleManagersMouseExited

    private void jMapleAdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapleAdminsMouseClicked
        // TODO add your handling code here:
        //Apply CSS
        jMapleManagers.setBackground(Color.white);
        jMapleAdmins.setBackground(Color.CYAN);
        
        try {
            //Refresh Table Data
            populateTableData("ADMIN");
        } catch (SQLException ex) {
            
        }
        
        adminClick = 1;
        managerClick = 0;
    }//GEN-LAST:event_jMapleAdminsMouseClicked

    private void jMapleAdminsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapleAdminsMouseEntered
        // TODO add your handling code here:
        jMapleAdmins.setBackground(Color.CYAN);
    }//GEN-LAST:event_jMapleAdminsMouseEntered

    private void jMapleAdminsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMapleAdminsMouseExited
        // TODO add your handling code here:
        if(adminClick==1 && managerClick==0 ){
            jMapleAdmins.setBackground(Color.CYAN);
            return;
        }
        jMapleAdmins.setBackground(Color.white);
        adminClick = 0;
    }//GEN-LAST:event_jMapleAdminsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLocation;
    private com.iris.ui.resources.Card jMapleAdmins;
    private com.iris.ui.resources.Card jMapleManagers;
    private com.iris.ui.resources.ButtonBadges jRefreshTableBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jTablePanel;
    private com.iris.ui.resources.Table table;
    // End of variables declaration//GEN-END:variables


}
