/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Admin;

import TheBusiness.Business.Business;
import TheBusiness.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminDashboardPanel extends javax.swing.JPanel {

    JPanel ContentPanel;
    Business business;
    UserAccount ua;

    /**
     * Creates new form UnitRiskWorkArea
     *
     * @param business
     * @param ua
     * @param ContentPanel
     */
    public AdminDashboardPanel(Business business, UserAccount ua,
            JPanel ContentPanel) {

        this.business = business;
        this.ContentPanel = ContentPanel;
        this.ua = ua;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBusinessButton = new javax.swing.JButton();
        viewSalesOrdersButton = new javax.swing.JButton();
        manageSupplierButton = new javax.swing.JButton();
        viewProductPriceButton = new javax.swing.JButton();
        manageCustomerButton = new javax.swing.JButton();
        performanceReportButton = new javax.swing.JButton();
        manageSalesPersonButton = new javax.swing.JButton();
        manageMarketingPersonButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        manageBusinessButton.setBackground(new java.awt.Color(102, 153, 255));
        manageBusinessButton.setFont(getFont());
        manageBusinessButton.setForeground(new java.awt.Color(255, 255, 255));
        manageBusinessButton.setText("Manage The Business");
        manageBusinessButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageBusinessButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageBusinessButton.setMinimumSize(new java.awt.Dimension(20, 23));
        manageBusinessButton.setPreferredSize(new java.awt.Dimension(240, 30));
        manageBusinessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBusinessButtonIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        viewSalesOrdersButton.setBackground(new java.awt.Color(102, 153, 255));
        viewSalesOrdersButton.setFont(getFont());
        viewSalesOrdersButton.setForeground(new java.awt.Color(255, 255, 255));
        viewSalesOrdersButton.setText("View Sales & Orders");
        viewSalesOrdersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewSalesOrdersButton.setMaximumSize(new java.awt.Dimension(200, 40));
        viewSalesOrdersButton.setMinimumSize(new java.awt.Dimension(20, 20));
        viewSalesOrdersButton.setPreferredSize(new java.awt.Dimension(240, 25));
        viewSalesOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesOrdersButtonActionPerformed(evt);
            }
        });

        manageSupplierButton.setBackground(new java.awt.Color(102, 153, 255));
        manageSupplierButton.setFont(getFont());
        manageSupplierButton.setForeground(new java.awt.Color(255, 255, 255));
        manageSupplierButton.setText("Manage Suppliers");
        manageSupplierButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageSupplierButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageSupplierButton.setMinimumSize(new java.awt.Dimension(20, 20));
        manageSupplierButton.setPreferredSize(new java.awt.Dimension(240, 25));
        manageSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSupplierButtonActionPerformed(evt);
            }
        });

        viewProductPriceButton.setBackground(new java.awt.Color(102, 153, 255));
        viewProductPriceButton.setFont(getFont());
        viewProductPriceButton.setForeground(new java.awt.Color(255, 255, 255));
        viewProductPriceButton.setText("View Product & Prices");
        viewProductPriceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewProductPriceButton.setMaximumSize(new java.awt.Dimension(145, 40));
        viewProductPriceButton.setMinimumSize(new java.awt.Dimension(20, 20));
        viewProductPriceButton.setPreferredSize(new java.awt.Dimension(240, 25));
        viewProductPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductPriceButtonIdentifyEventsActionPerformed(evt);
            }
        });

        manageCustomerButton.setBackground(new java.awt.Color(102, 153, 255));
        manageCustomerButton.setFont(getFont());
        manageCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        manageCustomerButton.setText("Manage Customers");
        manageCustomerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageCustomerButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageCustomerButton.setMinimumSize(new java.awt.Dimension(20, 20));
        manageCustomerButton.setPreferredSize(new java.awt.Dimension(240, 25));
        manageCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerButtonActionPerformed(evt);
            }
        });

        performanceReportButton.setBackground(new java.awt.Color(102, 153, 255));
        performanceReportButton.setFont(getFont());
        performanceReportButton.setForeground(new java.awt.Color(255, 255, 255));
        performanceReportButton.setText("Performance Reports");
        performanceReportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        performanceReportButton.setMaximumSize(new java.awt.Dimension(200, 40));
        performanceReportButton.setMinimumSize(new java.awt.Dimension(20, 20));
        performanceReportButton.setPreferredSize(new java.awt.Dimension(240, 25));
        performanceReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceReportButtonActionPerformed(evt);
            }
        });

        manageSalesPersonButton.setBackground(new java.awt.Color(102, 153, 255));
        manageSalesPersonButton.setFont(getFont());
        manageSalesPersonButton.setForeground(new java.awt.Color(255, 255, 255));
        manageSalesPersonButton.setText("Manage Sales Personnel");
        manageSalesPersonButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageSalesPersonButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageSalesPersonButton.setMinimumSize(new java.awt.Dimension(20, 23));
        manageSalesPersonButton.setPreferredSize(new java.awt.Dimension(240, 30));
        manageSalesPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSalesPersonButtonIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        manageMarketingPersonButton.setBackground(new java.awt.Color(102, 153, 255));
        manageMarketingPersonButton.setFont(getFont());
        manageMarketingPersonButton.setForeground(new java.awt.Color(255, 255, 255));
        manageMarketingPersonButton.setText("Manage Marketing Personnel");
        manageMarketingPersonButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageMarketingPersonButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageMarketingPersonButton.setMinimumSize(new java.awt.Dimension(20, 23));
        manageMarketingPersonButton.setPreferredSize(new java.awt.Dimension(240, 30));
        manageMarketingPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMarketingPersonButtonIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(performanceReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageSalesPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageBusinessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewSalesOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manageSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(manageCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewProductPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageMarketingPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageBusinessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageSupplierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageSalesPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageMarketingPersonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSalesOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProductPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(performanceReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBusinessButtonIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBusinessButtonIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        AdminManageBusinessPanel admManageBusPanel
                = new AdminManageBusinessPanel(business, ua, ContentPanel);
        ContentPanel.add("AdminManageBusinessPanel", admManageBusPanel);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
    }//GEN-LAST:event_manageBusinessButtonIdentifyResourceAssetsActionPerformed

    private void viewSalesOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesOrdersButtonActionPerformed
        // TODO add your handling code here:
        AdminViewSalesOrdersPanel salesOrderPanel
                = new AdminViewSalesOrdersPanel(business, ua, ContentPanel);
        ContentPanel.add("AdminViewSalesOrderPanel", salesOrderPanel);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
}//GEN-LAST:event_viewSalesOrdersButtonActionPerformed

    private void manageSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSupplierButtonActionPerformed
        // TODO add your handling code here:
        AdminManageSupplierCatalogPanel manageSupplier
                = new AdminManageSupplierCatalogPanel(business, ua, ContentPanel);
        ContentPanel.add("AdminManageSupplierPanel", manageSupplier);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
    }//GEN-LAST:event_manageSupplierButtonActionPerformed

    private void viewProductPriceButtonIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductPriceButtonIdentifyEventsActionPerformed
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
        AdminViewProductPricePanel managePrice = new AdminViewProductPricePanel(business, ua, ContentPanel);
        ContentPanel.add("AdminManagePricePanel", managePrice);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
}//GEN-LAST:event_viewProductPriceButtonIdentifyEventsActionPerformed

    private void manageCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerButtonActionPerformed
        AdminManageCustomerPanel manageCust
                = new AdminManageCustomerPanel(business, ua, ContentPanel);
        ContentPanel.add("AdminManageCustPanel", manageCust);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
}//GEN-LAST:event_manageCustomerButtonActionPerformed

    private void performanceReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceReportButtonActionPerformed

}//GEN-LAST:event_performanceReportButtonActionPerformed

    private void manageSalesPersonButtonIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSalesPersonButtonIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        AdminManageSalesPersonPanel salesPersonPanel
                = new AdminManageSalesPersonPanel(business, ua, ContentPanel);
        ContentPanel.add("AdminManageSalesPersonPanel", salesPersonPanel);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
    }//GEN-LAST:event_manageSalesPersonButtonIdentifyResourceAssetsActionPerformed

    private void manageMarketingPersonButtonIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMarketingPersonButtonIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        AdminManageMarketingPersonPanel markPersonPanel
                = new AdminManageMarketingPersonPanel(business, ua, ContentPanel);
        ContentPanel.add("AdminManageMarkPersonPanel", markPersonPanel);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
    }//GEN-LAST:event_manageMarketingPersonButtonIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageBusinessButton;
    private javax.swing.JButton manageCustomerButton;
    private javax.swing.JButton manageMarketingPersonButton;
    private javax.swing.JButton manageSalesPersonButton;
    private javax.swing.JButton manageSupplierButton;
    private javax.swing.JButton performanceReportButton;
    private javax.swing.JButton viewProductPriceButton;
    private javax.swing.JButton viewSalesOrdersButton;
    // End of variables declaration//GEN-END:variables

}
