/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.iris.ui.eventadmin;

import com.iris.backend.controller.EventController;
import com.iris.backend.controller.WorkRequestController;
import com.iris.backend.model.Event;
import com.iris.backend.model.User;
import com.iris.ui.HomeJPanel;
import com.iris.ui.HomeLeftJPanel;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JSplitPane;

/**
 *
 * @author sushanthkumarreddyjanga
 */

public class EventAdminScreen extends javax.swing.JPanel {
    
    JSplitPane mainSplitPane;
    
    WorkRequestController workRequestController;
    EventController eventController;
    ArrayList<User> userData;
    
    int eventAdminId;
    
    public EventAdminScreen(JSplitPane jSplitPane, ArrayList<User> userData) throws SQLException {
        initComponents();
        this.mainSplitPane = jSplitPane;
        workRequestController = new WorkRequestController();
        eventController = new EventController();
        this.userData = userData;
        eventAdminId = userData.get(0).getID();
        populateUserData();
        //Load Dashboard Screen (by default)
        EventAdminDashboard eventAdminDashboard = new EventAdminDashboard(userData);
        jRightSplitPane.setRightComponent(eventAdminDashboard);
    }
    
    public void populateUserData() throws SQLException{
        jUserImageIcon.setIcon(new ImageIcon(getClass().getResource("/com/iris/ui/icons/p1.jpg"))); //TODO: get userImage from backend
        jUserName.setText(userData.get(0).getName());
        getNotificationData();
    }
    public void getNotificationData() throws SQLException{
        // get notification count
        ArrayList<Event> publicPendingEventList = new ArrayList<>();
        eventController.getPublicEventList().stream()
                .filter(evt -> evt.getStatus().equalsIgnoreCase("PENDING"))
                .forEach(evt -> publicPendingEventList.add(evt));
        
        ArrayList<Event> privatePendingEventList = new ArrayList<>();
        eventController.getPrivateEventList().stream()
                .filter(evt -> evt.getStatus().equalsIgnoreCase("PENDING"))
                .forEach(evt -> privatePendingEventList.add(evt));
        int notification = publicPendingEventList.size() + privatePendingEventList.size();
        notificationBadge.setBadges(notification); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaseSplitPane = new javax.swing.JSplitPane();
        jBaseRightPanel = new javax.swing.JPanel();
        jRightSplitPane = new javax.swing.JSplitPane();
        jTopRightPanel = new javax.swing.JPanel();
        jUserImageIcon = new com.iris.ui.resources.ImageAvatar();
        jUserName = new javax.swing.JLabel();
        jUserRole = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        notificationBadge = new com.iris.ui.resources.ButtonBadges();
        messageBadge = new com.iris.ui.resources.ButtonBadges();
        burgerBadge = new com.iris.ui.resources.ButtonBadges();
        jBottonRightPanel = new javax.swing.JPanel();
        jBaseLeftPanel = new javax.swing.JPanel();
        mapleLogo = new com.iris.ui.resources.ImageAvatar();
        jDashboardBtn = new com.iris.ui.resources.Button();
        jRequestsBtn = new com.iris.ui.resources.Button();
        jLogoutBtn = new com.iris.ui.resources.Button();

        jBaseSplitPane.setDividerSize(0);
        jBaseSplitPane.setMaximumSize(new java.awt.Dimension(1100, 800));
        jBaseSplitPane.setMinimumSize(new java.awt.Dimension(1100, 800));
        jBaseSplitPane.setPreferredSize(new java.awt.Dimension(1100, 800));
        jBaseSplitPane.setRequestFocusEnabled(false);

        jRightSplitPane.setDividerSize(0);
        jRightSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jRightSplitPane.setMaximumSize(new java.awt.Dimension(985, 880));
        jRightSplitPane.setOpaque(false);
        jRightSplitPane.setPreferredSize(new java.awt.Dimension(985, 880));

        jTopRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        jTopRightPanel.setMaximumSize(new java.awt.Dimension(985, 80));
        jTopRightPanel.setMinimumSize(new java.awt.Dimension(985, 80));
        jTopRightPanel.setPreferredSize(new java.awt.Dimension(985, 80));

        jUserName.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jUserName.setForeground(new java.awt.Color(127, 127, 127));
        jUserName.setText("User Name");

        jUserRole.setForeground(new java.awt.Color(127, 127, 127));
        jUserRole.setText("Event Admin");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        notificationBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/notification.png")));
        notificationBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBadgeActionPerformed(evt);
            }
        });

        messageBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/message.png")));

        burgerBadge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/menu.png")));

        javax.swing.GroupLayout jTopRightPanelLayout = new javax.swing.GroupLayout(jTopRightPanel);
        jTopRightPanel.setLayout(jTopRightPanelLayout);
        jTopRightPanelLayout.setHorizontalGroup(
            jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopRightPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(burgerBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(620, 620, 620)
                .addComponent(messageBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUserName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUserRole, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jUserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jTopRightPanelLayout.setVerticalGroup(
            jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopRightPanelLayout.createSequentialGroup()
                .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUserRole))
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(jTopRightPanelLayout.createSequentialGroup()
                .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jUserImageIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jTopRightPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jTopRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notificationBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(burgerBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jRightSplitPane.setTopComponent(jTopRightPanel);

        jBottonRightPanel.setBackground(new java.awt.Color(245, 241, 241));
        jBottonRightPanel.setMaximumSize(new java.awt.Dimension(1100, 800));
        jBottonRightPanel.setMinimumSize(new java.awt.Dimension(1100, 800));
        jBottonRightPanel.setPreferredSize(new java.awt.Dimension(1100, 800));

        javax.swing.GroupLayout jBottonRightPanelLayout = new javax.swing.GroupLayout(jBottonRightPanel);
        jBottonRightPanel.setLayout(jBottonRightPanelLayout);
        jBottonRightPanelLayout.setHorizontalGroup(
            jBottonRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jBottonRightPanelLayout.setVerticalGroup(
            jBottonRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jRightSplitPane.setRightComponent(jBottonRightPanel);

        javax.swing.GroupLayout jBaseRightPanelLayout = new javax.swing.GroupLayout(jBaseRightPanel);
        jBaseRightPanel.setLayout(jBaseRightPanelLayout);
        jBaseRightPanelLayout.setHorizontalGroup(
            jBaseRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRightSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jBaseRightPanelLayout.setVerticalGroup(
            jBaseRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRightSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jBaseSplitPane.setRightComponent(jBaseRightPanel);

        jBaseLeftPanel.setBackground(new java.awt.Color(255, 255, 255));

        mapleLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/iris.jpg")));

        jDashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/dash.png")));
        jDashboardBtn.setText("Dashboard");
        jDashboardBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/1.png")));
        jDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDashboardBtnActionPerformed(evt);
            }
        });

        jRequestsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/analytics.png")));
        jRequestsBtn.setText("Requests");
        jRequestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRequestsBtnActionPerformed(evt);
            }
        });

        jLogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iris/ui/icons/logout.png")));
        jLogoutBtn.setText("Logout");
        jLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBaseLeftPanelLayout = new javax.swing.GroupLayout(jBaseLeftPanel);
        jBaseLeftPanel.setLayout(jBaseLeftPanelLayout);
        jBaseLeftPanelLayout.setHorizontalGroup(
            jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                .addGroup(jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mapleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBaseLeftPanelLayout.setVerticalGroup(
            jBaseLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBaseLeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mapleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRequestsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(jLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );

        jBaseSplitPane.setLeftComponent(jBaseLeftPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBaseSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void notificationBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBadgeActionPerformed
//        try {
//            BusinessAdminRequest businessAdminRequest = new BusinessAdminRequest(userData);
//            jRightSplitPane.setBottomComponent(businessAdminRequest);
//        } catch (SQLException ex) {}
    }//GEN-LAST:event_notificationBadgeActionPerformed

    private void jLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutBtnActionPerformed
        //Reset right panel
        HomeJPanel homeScreen = new HomeJPanel(this.mainSplitPane);
        this.mainSplitPane.setRightComponent(homeScreen);  
        //Reset left panel
        HomeLeftJPanel homeLeftPanel = new HomeLeftJPanel(this.mainSplitPane);
        this.mainSplitPane.setLeftComponent(homeLeftPanel);
    }//GEN-LAST:event_jLogoutBtnActionPerformed

    private void jRequestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRequestsBtnActionPerformed
        try {
            EventAdminRequest eventAdminRequest = new EventAdminRequest(userData);
            jRightSplitPane.setBottomComponent(eventAdminRequest);
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_jRequestsBtnActionPerformed

    private void jDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDashboardBtnActionPerformed
        try {
//            getNotificationData();
            EventAdminDashboard eventAdminDashboard = new EventAdminDashboard(userData);
            jRightSplitPane.setRightComponent(eventAdminDashboard);
        } catch (SQLException ex) {}
    }//GEN-LAST:event_jDashboardBtnActionPerformed

    public JSplitPane getBaseSplitPane(){
        return this.jBaseSplitPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.iris.ui.resources.ButtonBadges burgerBadge;
    private javax.swing.JPanel jBaseLeftPanel;
    private javax.swing.JPanel jBaseRightPanel;
    private javax.swing.JSplitPane jBaseSplitPane;
    private javax.swing.JPanel jBottonRightPanel;
    private com.iris.ui.resources.Button jDashboardBtn;
    private com.iris.ui.resources.Button jLogoutBtn;
    private com.iris.ui.resources.Button jRequestsBtn;
    private javax.swing.JSplitPane jRightSplitPane;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jTopRightPanel;
    private com.iris.ui.resources.ImageAvatar jUserImageIcon;
    private javax.swing.JLabel jUserName;
    private javax.swing.JLabel jUserRole;
    private com.iris.ui.resources.ImageAvatar mapleLogo;
    private com.iris.ui.resources.ButtonBadges messageBadge;
    private com.iris.ui.resources.ButtonBadges notificationBadge;
    // End of variables declaration//GEN-END:variables

}
