/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.professor;

import elearning.models.CourseModel;
import elearning.models.ProfCourseSubjectMapModel;
import elearning.models.ProfessorCourseModel;
import elearning.models.ProfessorDataModel;
import elearning.models.SemisterModel;
import elearning.models.UserDefaultDataModel;
import elearning.models.UserModel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aayuka Nirawade
 */
public class ProfessorRegisterCoursePanel extends javax.swing.JPanel {

    JPanel profContentPanel;
    UserDefaultDataModel userDefaultDataObj;
    ProfessorDataModel professorDataObj;
    UserModel userObj;

    /**
     * Creates new form RegisterCoursePanel
     *
     * @param profContentPanel
     * @param userDefaultDataObj
     * @param userObj
     * @param professorDataObj
     */
    public ProfessorRegisterCoursePanel(JPanel profContentPanel,
            UserDefaultDataModel userDefaultDataObj,
            UserModel userObj,
            ProfessorDataModel professorDataObj) {
        initComponents();
        this.profContentPanel = profContentPanel;
        this.userDefaultDataObj = userDefaultDataObj;
        this.userObj = userObj;
        this.professorDataObj = professorDataObj;

        this.courseOneTB.setVisible(false);
        this.courseTwoTB.setVisible(false);
        this.CloseCouserOneOtherButton.setVisible(false);
        this.CloseCouserTwoOtherButton.setVisible(false);

        loadTermDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        course_2_enddate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        subjectCB_1 = new javax.swing.JComboBox<>();
        courseCB_1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        course_1_stdate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        course_1_enddate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        courseCB_2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        course_2_stdate = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        termCB = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        subjectCB_2 = new javax.swing.JComboBox<>();
        courseOneTB = new javax.swing.JTextField();
        courseTwoTB = new javax.swing.JTextField();
        CloseCouserOneOtherButton = new javax.swing.JButton();
        CloseCouserTwoOtherButton = new javax.swing.JButton();

        jLabel7.setText("End Date  :");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subject 1", "Subject 2", "Subject 3", "Subject 4" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Save");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Register Course");

        jLabel2.setText("Professor Name  :");

        jLabel8.setText("Course Name  : ");

        jLabel3.setText("Stream/ Subject  :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course 1", "Course 2", "Course 3", "Course 4" }));

        jLabel9.setText("Start Date  :");

        jLabel4.setText("Course Details :");

        jLabel5.setText("Course Name  :");

        jLabel10.setText("End Date  :");

        jLabel6.setText("Start Date  :");

        jLabel11.setText("End Date  :");

        subjectCB_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subject 1", "Subject 2", "Subject 3", "Subject 4" }));
        subjectCB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCB_1ActionPerformed(evt);
            }
        });

        courseCB_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        courseCB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCB_1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Register Course");

        jLabel14.setText("Course Name  : ");

        jLabel15.setText("Stream/ Subject  :");

        courseCB_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        courseCB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCB_2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Start Date  :");

        jLabel17.setText("Course Details :");

        jLabel18.setText("Course Name  :");

        jLabel19.setText("End Date  :");

        jLabel20.setText("Start Date  :");

        jLabel13.setText("Term/ Semister  :");

        termCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        termCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termCBActionPerformed(evt);
            }
        });

        jLabel21.setText("Stream/ Subject  :");

        subjectCB_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        subjectCB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCB_2ActionPerformed(evt);
            }
        });

        CloseCouserOneOtherButton.setForeground(new java.awt.Color(255, 0, 51));
        CloseCouserOneOtherButton.setText("X");
        CloseCouserOneOtherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseCouserOneOtherButtonActionPerformed(evt);
            }
        });

        CloseCouserTwoOtherButton.setForeground(new java.awt.Color(255, 0, 51));
        CloseCouserTwoOtherButton.setText("X");
        CloseCouserTwoOtherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseCouserTwoOtherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(termCB, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(0, 435, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(subjectCB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(course_1_stdate)
                                                    .addComponent(course_1_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(courseCB_1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGap(47, 47, 47))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(courseOneTB, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CloseCouserOneOtherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(courseCB_2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel19))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(course_2_stdate)
                                            .addComponent(course_2_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(subjectCB_2, 0, 253, Short.MAX_VALUE)
                                    .addComponent(jLabel21)
                                    .addComponent(courseTwoTB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CloseCouserTwoOtherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(termCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectCB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectCB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCB_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseCB_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseOneTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseTwoTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseCouserOneOtherButton)
                    .addComponent(CloseCouserTwoOtherButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(course_1_stdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(course_2_stdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(course_1_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(course_2_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void termCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termCBActionPerformed
        // TODO add your handling code here:
        if (this.termCB.getSelectedItem() != null) {
            String termName = this.termCB.getSelectedItem().toString();
            if (termName.equalsIgnoreCase("--Select--")) {
                this.termCB.removeAllItems();
            } else {
                loadSubjectDetails(termName);
            }
        }
    }//GEN-LAST:event_termCBActionPerformed

    private void courseCB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCB_2ActionPerformed
        // TODO add your handling code here:
        if (this.courseCB_2.getSelectedItem() != null) {
            String courseName = this.courseCB_2.getSelectedItem().toString();
            if (courseName.equalsIgnoreCase("other")) {
                this.courseCB_2.setVisible(false);
                this.courseTwoTB.setVisible(true);
                this.CloseCouserTwoOtherButton.setVisible(true);
            } else {
                this.courseCB_2.setVisible(true);
                this.courseTwoTB.setVisible(false);
                this.CloseCouserTwoOtherButton.setVisible(false);
            }
        }
    }//GEN-LAST:event_courseCB_2ActionPerformed

    private void subjectCB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCB_1ActionPerformed
        // TODO add your handling code here:
        if (this.subjectCB_1.getSelectedItem() != null) {
            String termName = this.termCB.getSelectedItem().toString();
            String subName = this.subjectCB_1.getSelectedItem().toString();
            if (termName.equalsIgnoreCase("--Select--")) {
                this.subjectCB_1.removeAllItems();
                this.subjectCB_2.removeAllItems();
            } else if (!(termName.equalsIgnoreCase("--Select--"))
                    && !(subName.equalsIgnoreCase("--Select--"))) {
                loadCourse_1_Details(termName, subName);
            }
        }
    }//GEN-LAST:event_subjectCB_1ActionPerformed

    private void subjectCB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCB_2ActionPerformed
        // TODO add your handling code here:
        if (this.subjectCB_2.getSelectedItem() != null) {
            String termName = this.termCB.getSelectedItem().toString();
            String subName = this.subjectCB_2.getSelectedItem().toString();
            if (termName.equalsIgnoreCase("--Select--")) {
                this.subjectCB_1.removeAllItems();
                this.subjectCB_2.removeAllItems();
            } else if (!(termName.equalsIgnoreCase("--Select--"))
                    && !(subName.equalsIgnoreCase("--Select--"))) {
                loadCourse_2_Details(termName, subName);
            }
        }
    }//GEN-LAST:event_subjectCB_2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String termName = this.termCB.getSelectedItem().toString();
        String sub_1_Name = this.subjectCB_1.getSelectedItem().toString();
        String sub_2_Name = this.subjectCB_2.getSelectedItem().toString();
        String course_1_Name = this.courseCB_1.getSelectedItem().toString();
        String course_2_Name = this.courseCB_2.getSelectedItem().toString();
        String courseOneStdate = this.course_1_stdate.getText();
        String courseOneEnddate = this.course_1_enddate.getText();
        String courseTwoStdate = this.course_2_stdate.getText();
        String courseTwoEnddate = this.course_2_enddate.getText();

        if (course_1_Name.equalsIgnoreCase("other")) {
            course_1_Name = this.courseOneTB.getText();
            CourseModel courseObj = new CourseModel(sub_1_Name, course_1_Name, "3");
            if (this.userDefaultDataObj.getSemisterSubList() != null
                    && !this.userDefaultDataObj.getSemisterSubList().isEmpty()) {
                for (SemisterModel semisObj : this.userDefaultDataObj.getSemisterSubList()) {
                    if (semisObj.getSemisterName().equalsIgnoreCase(termName)) {
                        semisObj.getSubjects().add(courseObj);
                    }
                }
            }
        }
        if (course_2_Name.equalsIgnoreCase("other")) {
            course_2_Name = this.courseTwoTB.getText();
            CourseModel courseObj = new CourseModel(sub_2_Name, course_2_Name, "3");
            if (this.userDefaultDataObj.getSemisterSubList() != null
                    && !this.userDefaultDataObj.getSemisterSubList().isEmpty()) {
                for (SemisterModel semisObj : this.userDefaultDataObj.getSemisterSubList()) {
                    if (semisObj.getSemisterName().equalsIgnoreCase(termName)) {
                        semisObj.getSubjects().add(courseObj);
                    }
                }
            }
        }

        ProfessorCourseModel profCourseObj = new ProfessorCourseModel();

        profCourseObj.setProfessorName(userObj.getFullName());
        profCourseObj.setSemisterName(termName);
        profCourseObj.setSubjectOne(sub_1_Name);

        ProfCourseSubjectMapModel profSubOneObj = new ProfCourseSubjectMapModel();
        ProfCourseSubjectMapModel profSubTwoObj = new ProfCourseSubjectMapModel();

        profSubOneObj.setCourseName(course_1_Name);
        profSubOneObj.setSubjectName(sub_1_Name);
        profSubOneObj.setStartDate(courseOneStdate);
        profSubOneObj.setEndDate(courseOneEnddate);
        profSubOneObj.setStatus("Planned");

        profSubTwoObj.setCourseName(course_2_Name);
        profSubTwoObj.setSubjectName(sub_2_Name);
        profSubTwoObj.setStartDate(courseTwoStdate);
        profSubTwoObj.setEndDate(courseTwoEnddate);
        profSubTwoObj.setStatus("Planned");

        List<ProfCourseSubjectMapModel> profCourseSubjectLi = new ArrayList<>();
        if (!course_1_Name.equalsIgnoreCase("--Select--") && !sub_1_Name.equalsIgnoreCase("--Select")) {
            profCourseSubjectLi.add(profSubOneObj);
        }
        if (!course_2_Name.equalsIgnoreCase("--Select--") && !sub_2_Name.equalsIgnoreCase("--Select")) {
            profCourseSubjectLi.add(profSubTwoObj);
        }

        profCourseObj.setProfCourseSubjectLi(profCourseSubjectLi);

        professorDataObj.getProfessorCourseLi().add(profCourseObj);

        JOptionPane.showMessageDialog(null, "Course Details Added Successfully!");

        ProfessorTeachingHistoryPanel tachingHistory = new ProfessorTeachingHistoryPanel(
                profContentPanel, professorDataObj, userObj);
        profContentPanel.add("ProfTeachingHistory", tachingHistory);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void courseCB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCB_1ActionPerformed
        // TODO add your handling code here:
        if (this.courseCB_1.getSelectedItem() != null) {
            String course_1_Name = this.courseCB_1.getSelectedItem().toString();
            if (course_1_Name.equalsIgnoreCase("other")) {
                this.courseCB_1.setVisible(false);
                this.courseOneTB.setVisible(true);
                this.CloseCouserOneOtherButton.setVisible(true);
            } else {
                this.courseCB_1.setVisible(true);
                this.courseOneTB.setVisible(false);
                this.CloseCouserOneOtherButton.setVisible(false);
            }
        }
    }//GEN-LAST:event_courseCB_1ActionPerformed

    private void CloseCouserOneOtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseCouserOneOtherButtonActionPerformed
        // TODO add your handling code here:
        this.courseCB_1.setVisible(true);
        this.courseCB_1.setSelectedIndex(0);
        this.courseOneTB.setVisible(false);
        this.courseOneTB.setText("");
        this.CloseCouserOneOtherButton.setVisible(false);
    }//GEN-LAST:event_CloseCouserOneOtherButtonActionPerformed

    private void CloseCouserTwoOtherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseCouserTwoOtherButtonActionPerformed
        // TODO add your handling code here:
        this.courseCB_2.setVisible(true);
        this.courseCB_2.setSelectedIndex(0);
        this.courseTwoTB.setVisible(false);
        this.courseTwoTB.setText("");
        this.CloseCouserTwoOtherButton.setVisible(false);
    }//GEN-LAST:event_CloseCouserTwoOtherButtonActionPerformed

    private void loadTermDetails() {
        if (this.userDefaultDataObj.getSemisterSubList() != null
                && !this.userDefaultDataObj.getSemisterSubList().isEmpty()) {
            DefaultComboBoxModel dcb = (DefaultComboBoxModel) termCB.getModel();
            dcb.removeAllElements();
            dcb.addElement("--Select--");
            for (SemisterModel semisterObj : this.userDefaultDataObj.getSemisterSubList()) {
                dcb.addElement(semisterObj.getSemisterName());
            }
        }
    }

    private void loadSubjectDetails(final String termName) {
        if (this.userDefaultDataObj.getSemisterSubList() != null
                && !this.userDefaultDataObj.getSemisterSubList().isEmpty()) {
            DefaultComboBoxModel subcb_1 = (DefaultComboBoxModel) subjectCB_1.getModel();
            subcb_1.removeAllElements();
            subcb_1.addElement("--Select--");

            DefaultComboBoxModel subcb_2 = (DefaultComboBoxModel) subjectCB_2.getModel();
            subcb_2.removeAllElements();
            subcb_2.addElement("--Select--");

            for (SemisterModel semisterObj : this.userDefaultDataObj.getSemisterSubList()) {
                if (semisterObj.getSemisterName().equalsIgnoreCase(termName)) {
                    for (CourseModel courseObj : semisterObj.getSubjects()) {
                        subcb_1.addElement(courseObj.getSubjectName());
                        subcb_2.addElement(courseObj.getSubjectName());
                    }
                }
            }
        }
    }

    private void loadCourse_1_Details(final String termName, final String subjectName) {
        if (this.userDefaultDataObj.getSemisterSubList() != null
                && !this.userDefaultDataObj.getSemisterSubList().isEmpty()) {
            DefaultComboBoxModel coursecb_1 = (DefaultComboBoxModel) courseCB_1.getModel();
            coursecb_1.removeAllElements();
            coursecb_1.addElement("--Select--");

            for (SemisterModel semisterObj : this.userDefaultDataObj.getSemisterSubList()) {
                if (semisterObj.getSemisterName().equalsIgnoreCase(termName)) {
                    for (CourseModel courseObj : semisterObj.getSubjects()) {
                        if (courseObj.getSubjectName().equalsIgnoreCase(subjectName)) {
                            coursecb_1.addElement(courseObj.getCourseName());
                        }
                    }
                }
            }
            coursecb_1.addElement("other");
        }
    }

    private void loadCourse_2_Details(final String termName, final String subjectName) {
        if (this.userDefaultDataObj.getSemisterSubList() != null
                && !this.userDefaultDataObj.getSemisterSubList().isEmpty()) {
            DefaultComboBoxModel coursecb_2 = (DefaultComboBoxModel) courseCB_2.getModel();
            coursecb_2.removeAllElements();
            coursecb_2.addElement("--Select--");

            for (SemisterModel semisterObj : this.userDefaultDataObj.getSemisterSubList()) {
                if (semisterObj.getSemisterName().equalsIgnoreCase(termName)) {
                    for (CourseModel courseObj : semisterObj.getSubjects()) {
                        if (courseObj.getSubjectName().equalsIgnoreCase(subjectName)) {
                            coursecb_2.addElement(courseObj.getCourseName());
                        }
                    }
                }
            }
            coursecb_2.addElement("other");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseCouserOneOtherButton;
    private javax.swing.JButton CloseCouserTwoOtherButton;
    private javax.swing.JComboBox<String> courseCB_1;
    private javax.swing.JComboBox<String> courseCB_2;
    private javax.swing.JTextField courseOneTB;
    private javax.swing.JTextField courseTwoTB;
    private javax.swing.JTextField course_1_enddate;
    private javax.swing.JTextField course_1_stdate;
    private javax.swing.JTextField course_2_enddate;
    private javax.swing.JTextField course_2_stdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> subjectCB_1;
    private javax.swing.JComboBox<String> subjectCB_2;
    private javax.swing.JComboBox<String> termCB;
    // End of variables declaration//GEN-END:variables
}
