/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.professor;

import elearning.models.ProfessorDataModel;
import elearning.models.StudentDataModel;
import elearning.models.UserDefaultDataModel;
import elearning.models.UserModel;
import elearning.models.UserSignUpModel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harsh
 */
public class ProfessorDashboardPanel extends javax.swing.JPanel {

    JPanel appContainerPanel;
    UserSignUpModel userSignUpObj;
    UserModel userObj;
    UserDefaultDataModel userDefaultDataObj;
    ProfessorDataModel professorDataObj;
    StudentDataModel studentDataObj;

    /**
     * Creates new form ProfessorDashboardPanel
     *
     * @param appContainerPanel
     * @param userSignUpObj
     * @param userObj
     * @param userDefaultDataObj
     * @param professorDataObj
     * @param studentDataObj
     */
    public ProfessorDashboardPanel(JPanel appContainerPanel,
            UserSignUpModel userSignUpObj, UserModel userObj,
            UserDefaultDataModel userDefaultDataObj,
            ProfessorDataModel professorDataObj,
            StudentDataModel studentDataObj) {
        initComponents();
        this.appContainerPanel = appContainerPanel;
        this.userSignUpObj = userSignUpObj;
        this.userObj = userObj;
        this.userDefaultDataObj = userDefaultDataObj;
        this.professorDataObj = professorDataObj;
        this.studentDataObj = studentDataObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        profMenuPanel = new javax.swing.JPanel();
        profCourseCatlogButton = new javax.swing.JButton();
        profRegisterCourseButton = new javax.swing.JButton();
        profManageCourseButton = new javax.swing.JButton();
        profTeachingHistoryButton = new javax.swing.JButton();
        profViewStudentsButton = new javax.swing.JButton();
        profProfileButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ManageSubjectsButton = new javax.swing.JButton();
        profContentPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        profMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        profMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        profCourseCatlogButton.setBackground(new java.awt.Color(51, 153, 255));
        profCourseCatlogButton.setText("Course Catalog");
        profCourseCatlogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profCourseCatlogButtonActionPerformed(evt);
            }
        });

        profRegisterCourseButton.setBackground(new java.awt.Color(51, 153, 255));
        profRegisterCourseButton.setText("Register Course");
        profRegisterCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profRegisterCourseButtonActionPerformed(evt);
            }
        });

        profManageCourseButton.setBackground(new java.awt.Color(51, 153, 255));
        profManageCourseButton.setText("Manage Course");
        profManageCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profManageCourseButtonActionPerformed(evt);
            }
        });

        profTeachingHistoryButton.setBackground(new java.awt.Color(51, 153, 255));
        profTeachingHistoryButton.setText("Teaching History");
        profTeachingHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profTeachingHistoryButtonActionPerformed(evt);
            }
        });

        profViewStudentsButton.setBackground(new java.awt.Color(51, 153, 255));
        profViewStudentsButton.setText("View Students");
        profViewStudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profViewStudentsButtonActionPerformed(evt);
            }
        });

        profProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        profProfileButton.setText("Profile");
        profProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profProfileButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Grade Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ManageSubjectsButton.setBackground(new java.awt.Color(51, 153, 255));
        ManageSubjectsButton.setText("Manage Subjects");
        ManageSubjectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSubjectsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profMenuPanelLayout = new javax.swing.GroupLayout(profMenuPanel);
        profMenuPanel.setLayout(profMenuPanelLayout);
        profMenuPanelLayout.setHorizontalGroup(
            profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profCourseCatlogButton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(ManageSubjectsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(profMenuPanelLayout.createSequentialGroup()
                        .addComponent(profTeachingHistoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profMenuPanelLayout.createSequentialGroup()
                        .addComponent(profRegisterCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(profManageCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profViewStudentsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        profMenuPanelLayout.setVerticalGroup(
            profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profMenuPanelLayout.createSequentialGroup()
                .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profProfileButton)
                    .addGroup(profMenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(profCourseCatlogButton)
                            .addComponent(profTeachingHistoryButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(profMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profRegisterCourseButton)
                    .addComponent(profManageCourseButton)
                    .addComponent(profViewStudentsButton)
                    .addComponent(jButton1)
                    .addComponent(ManageSubjectsButton))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(profMenuPanel);

        profContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        profContentPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(profContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void profCourseCatlogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profCourseCatlogButtonActionPerformed
        // TODO add your handling code here:
        ProfCourseCatalogPanel courseCatalog = new ProfCourseCatalogPanel(
                profContentPanel, this.userDefaultDataObj);
        profContentPanel.add("ProfCourseCatalog", courseCatalog);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profCourseCatlogButtonActionPerformed

    private void profProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profProfileButtonActionPerformed
        // TODO add your handling code here:
        ProfessorProfileResetPanel profProfileReset = new ProfessorProfileResetPanel(
                appContainerPanel, profContentPanel, userObj, userSignUpObj);
        profContentPanel.add("ProfProfileReset", profProfileReset);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profProfileButtonActionPerformed

    private void profRegisterCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profRegisterCourseButtonActionPerformed
        // TODO add your handling code here:
        ProfessorRegisterCoursePanel registerCourse = new ProfessorRegisterCoursePanel(
                profContentPanel, userDefaultDataObj, userObj, professorDataObj);
        profContentPanel.add("ProfRegisterCourse", registerCourse);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profRegisterCourseButtonActionPerformed

    private void profTeachingHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profTeachingHistoryButtonActionPerformed
        // TODO add your handling code here:
        ProfessorTeachingHistoryPanel tachingHistory = new ProfessorTeachingHistoryPanel(
                profContentPanel, professorDataObj, userObj);
        profContentPanel.add("ProfTeachingHistory", tachingHistory);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profTeachingHistoryButtonActionPerformed

    private void profViewStudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profViewStudentsButtonActionPerformed
        // TODO add your handling code here:
        ProfViewStudentsPanel viewStudents = new ProfViewStudentsPanel(
                profContentPanel, userObj, professorDataObj, studentDataObj);
        profContentPanel.add("ProfViewStudents", viewStudents);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profViewStudentsButtonActionPerformed

    private void profManageCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profManageCourseButtonActionPerformed
        // TODO add your handling code here:
        ProfessorManageCoursePanel manageCourse = new ProfessorManageCoursePanel(
                profContentPanel, userDefaultDataObj, userObj, professorDataObj, studentDataObj);

        profContentPanel.add("ProfManageCourse", manageCourse);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_profManageCourseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProfGradeStudentsPanel gradeStudent = new ProfGradeStudentsPanel(
                profContentPanel, userObj, userSignUpObj, studentDataObj);
        profContentPanel.add("ProfGradeStudent", gradeStudent);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ManageSubjectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSubjectsButtonActionPerformed
        // TODO add your handling code here:
        ProfManageSubjectPanel manageSub = new ProfManageSubjectPanel(
                profContentPanel, userDefaultDataObj);
        profContentPanel.add("ProfManageSubject", manageSub);
        CardLayout layout = (CardLayout) profContentPanel.getLayout();
        layout.next(profContentPanel);
    }//GEN-LAST:event_ManageSubjectsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageSubjectsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel profContentPanel;
    private javax.swing.JButton profCourseCatlogButton;
    private javax.swing.JButton profManageCourseButton;
    private javax.swing.JPanel profMenuPanel;
    private javax.swing.JButton profProfileButton;
    private javax.swing.JButton profRegisterCourseButton;
    private javax.swing.JButton profTeachingHistoryButton;
    private javax.swing.JButton profViewStudentsButton;
    // End of variables declaration//GEN-END:variables
}
