/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.Sales;

import UserInterface.Admin.*;
import TheBusiness.Business.Business;
import TheBusiness.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class SalesDashboardPanel extends javax.swing.JPanel {

    JPanel ContentPanel;
    Business business;
    UserAccount ua;

    /**
     * Creates new form UnitRiskWorkArea
     *
     * @param business
     * @param ua
     * @param ContentPanel
     */
    public SalesDashboardPanel(Business business, UserAccount ua,
            JPanel ContentPanel) {

        this.business = business;
        this.ContentPanel = ContentPanel;
        this.ua = ua;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSalesOrdersButton = new javax.swing.JButton();
        viewProductPriceButton = new javax.swing.JButton();
        manageCustomerButton = new javax.swing.JButton();
        performanceReportButton = new javax.swing.JButton();
        manageOrdersButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));

        viewSalesOrdersButton.setBackground(new java.awt.Color(102, 153, 255));
        viewSalesOrdersButton.setFont(getFont());
        viewSalesOrdersButton.setForeground(new java.awt.Color(255, 255, 255));
        viewSalesOrdersButton.setText("View Sales & Orders");
        viewSalesOrdersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewSalesOrdersButton.setMaximumSize(new java.awt.Dimension(200, 40));
        viewSalesOrdersButton.setMinimumSize(new java.awt.Dimension(20, 20));
        viewSalesOrdersButton.setPreferredSize(new java.awt.Dimension(240, 25));
        viewSalesOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSalesOrdersButtonActionPerformed(evt);
            }
        });

        viewProductPriceButton.setBackground(new java.awt.Color(102, 153, 255));
        viewProductPriceButton.setFont(getFont());
        viewProductPriceButton.setForeground(new java.awt.Color(255, 255, 255));
        viewProductPriceButton.setText("View Product & Prices");
        viewProductPriceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewProductPriceButton.setMaximumSize(new java.awt.Dimension(145, 40));
        viewProductPriceButton.setMinimumSize(new java.awt.Dimension(20, 20));
        viewProductPriceButton.setPreferredSize(new java.awt.Dimension(240, 25));
        viewProductPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductPriceButtonIdentifyEventsActionPerformed(evt);
            }
        });

        manageCustomerButton.setBackground(new java.awt.Color(102, 153, 255));
        manageCustomerButton.setFont(getFont());
        manageCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        manageCustomerButton.setText("Manage Customers");
        manageCustomerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageCustomerButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageCustomerButton.setMinimumSize(new java.awt.Dimension(20, 20));
        manageCustomerButton.setPreferredSize(new java.awt.Dimension(240, 25));
        manageCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerButtonActionPerformed(evt);
            }
        });

        performanceReportButton.setBackground(new java.awt.Color(102, 153, 255));
        performanceReportButton.setFont(getFont());
        performanceReportButton.setForeground(new java.awt.Color(255, 255, 255));
        performanceReportButton.setText("Performance Reports");
        performanceReportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        performanceReportButton.setMaximumSize(new java.awt.Dimension(200, 40));
        performanceReportButton.setMinimumSize(new java.awt.Dimension(20, 20));
        performanceReportButton.setPreferredSize(new java.awt.Dimension(240, 25));
        performanceReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceReportButtonActionPerformed(evt);
            }
        });

        manageOrdersButton.setBackground(new java.awt.Color(102, 153, 255));
        manageOrdersButton.setFont(getFont());
        manageOrdersButton.setForeground(new java.awt.Color(255, 255, 255));
        manageOrdersButton.setText("Manage Orders");
        manageOrdersButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageOrdersButton.setMaximumSize(new java.awt.Dimension(200, 40));
        manageOrdersButton.setMinimumSize(new java.awt.Dimension(20, 20));
        manageOrdersButton.setPreferredSize(new java.awt.Dimension(240, 25));
        manageOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewSalesOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProductPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(performanceReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(manageOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProductPriceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSalesOrdersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(performanceReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewSalesOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSalesOrdersButtonActionPerformed
        // TODO add your handling code here:
        SaleViewSalesOrdersPanel salesOrderPanel
                = new SaleViewSalesOrdersPanel(business, ua, ContentPanel);
        ContentPanel.add("SaleViewSalesOrderPanel", salesOrderPanel);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
}//GEN-LAST:event_viewSalesOrdersButtonActionPerformed

    private void viewProductPriceButtonIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductPriceButtonIdentifyEventsActionPerformed
        //((java.awt.CardLayout)CardSequencePanel.getLayout()).show(CardSequencePanel, "IdentifyEventTypes");
        SalesViewProductPricePanel managePrice
                = new SalesViewProductPricePanel(business, ua, ContentPanel);
        ContentPanel.add("SaleManagePricePanel", managePrice);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
}//GEN-LAST:event_viewProductPriceButtonIdentifyEventsActionPerformed

    private void manageCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerButtonActionPerformed
        SaleManageCustomerPanel manageCust
                = new SaleManageCustomerPanel(business, ua, ContentPanel);
        ContentPanel.add("SaleManageCustPanel", manageCust);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
}//GEN-LAST:event_manageCustomerButtonActionPerformed

    private void performanceReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceReportButtonActionPerformed

}//GEN-LAST:event_performanceReportButtonActionPerformed

    private void manageOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersButtonActionPerformed
        // TODO add your handling code here:
        SaleManageOrdersPanel manageOrd = 
                new SaleManageOrdersPanel(business, ua, ContentPanel);
        ContentPanel.add("SaleManageOrdsPanel", manageOrd);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);
    }//GEN-LAST:event_manageOrdersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageCustomerButton;
    private javax.swing.JButton manageOrdersButton;
    private javax.swing.JButton performanceReportButton;
    private javax.swing.JButton viewProductPriceButton;
    private javax.swing.JButton viewSalesOrdersButton;
    // End of variables declaration//GEN-END:variables

}
