/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.student;

import elearning.models.ProfessorDataModel;
import elearning.models.StudentCertModel;
import elearning.models.StudentDataModel;
import elearning.models.UserDefaultDataModel;
import elearning.models.UserModel;
import elearning.models.UserSignUpModel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harsh
 */
public class StudentDashboardPanel extends javax.swing.JPanel {

    JPanel appContainerPanel;
    UserSignUpModel userSignUpObj;
    UserModel userObj;
    UserDefaultDataModel userDefaultDataObj;
    ProfessorDataModel professorDataObj;
    StudentDataModel studentDataObj;

    /**
     * Creates new form StudentDashboardPanel
     *
     * @param appContainerPanel
     * @param userSignUpObj
     * @param userObj
     * @param userDefaultDataObj
     * @param professorDataObj
     * @param studentDataObj
     */
    public StudentDashboardPanel(JPanel appContainerPanel,
            UserSignUpModel userSignUpObj, UserModel userObj,
            UserDefaultDataModel userDefaultDataObj,
            ProfessorDataModel professorDataObj,
            StudentDataModel studentDataObj) {
        initComponents();
        this.appContainerPanel = appContainerPanel;
        this.userSignUpObj = userSignUpObj;
        this.userObj = userObj;
        this.userDefaultDataObj = userDefaultDataObj;
        this.professorDataObj = professorDataObj;
        this.studentDataObj = studentDataObj;

        if (this.studentDataObj.getStudentCertObj() != null
                && !this.studentDataObj.getStudentCertObj().isEmpty()) {
            for (StudentCertModel studentCertObj : this.studentDataObj.getStudentCertObj()) {
                if (studentCertObj.getStudentName().equalsIgnoreCase(userObj.getUsername())) {
                    if ((studentCertObj.getIssueCertificateFlg() != null
                            && studentCertObj.getIssueCertificateFlg().equalsIgnoreCase("I"))
                            || (studentCertObj.getReqCertificateFlg() != null
                            && studentCertObj.getReqCertificateFlg().equalsIgnoreCase("R"))) {
                        this.RegisterCourseButton.setVisible(false);
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        studentMenuPanel = new javax.swing.JPanel();
        studentProfileButton = new javax.swing.JButton();
        CourseCatalogButton = new javax.swing.JButton();
        RegisterCourseButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        StudentProfListButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        studentContentPanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(90);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        studentMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        studentProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        studentProfileButton.setText("Profile");
        studentProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentProfileButtonActionPerformed(evt);
            }
        });

        CourseCatalogButton.setBackground(new java.awt.Color(51, 153, 255));
        CourseCatalogButton.setText("Course Catalog");
        CourseCatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseCatalogButtonActionPerformed(evt);
            }
        });

        RegisterCourseButton.setBackground(new java.awt.Color(51, 153, 255));
        RegisterCourseButton.setText("Register Course");
        RegisterCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCourseButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Transcript");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setText("Certification Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        StudentProfListButton.setBackground(new java.awt.Color(0, 153, 255));
        StudentProfListButton.setText("Professor List");
        StudentProfListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentProfListButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setText("Rate Professor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentMenuPanelLayout = new javax.swing.GroupLayout(studentMenuPanel);
        studentMenuPanel.setLayout(studentMenuPanelLayout);
        studentMenuPanelLayout.setHorizontalGroup(
            studentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentProfileButton)
                .addContainerGap())
            .addGroup(studentMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CourseCatalogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StudentProfListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentMenuPanelLayout.setVerticalGroup(
            studentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(studentMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseCatalogButton)
                    .addComponent(RegisterCourseButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(StudentProfListButton)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(studentMenuPanel);

        studentContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        studentContentPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(studentContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void studentProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentProfileButtonActionPerformed
        // TODO add your handling code here:
        StudentProfileResetPanel studentProfile = new StudentProfileResetPanel(
                appContainerPanel, studentContentPanel, userObj, userSignUpObj);
        studentContentPanel.add("StudentProfileReset", studentProfile);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_studentProfileButtonActionPerformed

    private void CourseCatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseCatalogButtonActionPerformed
        // TODO add your handling code here:
        StudentCourseCatalogPanel courseCatalog = new StudentCourseCatalogPanel(
                studentContentPanel, userDefaultDataObj);
        studentContentPanel.add("StudentCourseCatalog", courseCatalog);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);

    }//GEN-LAST:event_CourseCatalogButtonActionPerformed

    private void StudentProfListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentProfListButtonActionPerformed
        // TODO add your handling code here:
        StudentProfessorListPanel studentProfList = new StudentProfessorListPanel(
                studentContentPanel, professorDataObj);
        studentContentPanel.add("StudentProfessorList", studentProfList);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_StudentProfListButtonActionPerformed

    private void RegisterCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCourseButtonActionPerformed
        // TODO add your handling code here:
        StudentCourseRegisterPanel registerCourse = new StudentCourseRegisterPanel(
                studentContentPanel, professorDataObj, userDefaultDataObj, userObj, studentDataObj);
        studentContentPanel.add("StudentRegisterCourse", registerCourse);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_RegisterCourseButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentTarnscriptPanel transciptPanel = new StudentTarnscriptPanel(
                studentContentPanel, studentDataObj, userObj);
        studentContentPanel.add("StudentTarnscript", transciptPanel);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StudentCertificateRequestPanel certificateReq = new StudentCertificateRequestPanel(
                studentContentPanel, studentDataObj, userObj);
        studentContentPanel.add("StudentCertReq", certificateReq);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        StudentRateProfessorPanel rateProf = new StudentRateProfessorPanel(
                studentContentPanel, professorDataObj, userDefaultDataObj, userObj, studentDataObj);
        studentContentPanel.add("StudentRateProf", rateProf);
        CardLayout layout = (CardLayout) studentContentPanel.getLayout();
        layout.next(studentContentPanel);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CourseCatalogButton;
    private javax.swing.JButton RegisterCourseButton;
    private javax.swing.JButton StudentProfListButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel studentContentPanel;
    private javax.swing.JPanel studentMenuPanel;
    private javax.swing.JButton studentProfileButton;
    // End of variables declaration//GEN-END:variables
}
