/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Main;

import TheBusiness.Business.Business;
import TheBusiness.UserAccountManagement.UserAccount;
import TheBusiness.UserAccountManagement.UserAccountDirectory;
import UserInterface.Admin.AdminDashboardPanel;
import UserInterface.Markets.MarketDashboardPanel;
import UserInterface.Sales.SalesDashboardPanel;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author harsh
 */
public class LoginPanel extends javax.swing.JPanel {

    private final Business business;
    JButton loginButton;
    JButton logoutButton;
    JLabel welcomLB;
    JPanel ContentPanel;

    /**
     * Creates new form LoginPanel
     *
     * @param loginButton
     * @param logoutButton
     * @param welcomLB
     * @param ContentPanel
     */
    public LoginPanel(JButton loginButton, JButton logoutButton,
            JLabel welcomLB, JPanel ContentPanel) {
        initComponents();

        errorLB.setVisible(false);
        errorLB1.setVisible(false);

        this.ContentPanel = ContentPanel;
        this.loginButton = loginButton;
        this.logoutButton = logoutButton;
        this.welcomLB = welcomLB;

        this.errorLB.setVisible(false);
        this.errorLB.setText("");
        this.business = ConfigureABusiness.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        usernameLB = new javax.swing.JLabel();
        usernameTB = new javax.swing.JTextField();
        passwordLB = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        errorLB = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        usernameLB1 = new javax.swing.JLabel();
        usernameTB1 = new javax.swing.JTextField();
        passwordLB1 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        errorLB1 = new javax.swing.JLabel();
        LoginButton1 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("LOGIN");

        usernameLB.setBackground(new java.awt.Color(102, 102, 102));
        usernameLB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLB.setText("Username :");

        usernameTB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTB.setForeground(new java.awt.Color(102, 102, 102));

        passwordLB.setBackground(new java.awt.Color(102, 102, 102));
        passwordLB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLB.setText("Password :");

        errorLB.setForeground(new java.awt.Color(255, 51, 51));
        errorLB.setText("Invalid Credentails ...");

        LoginButton.setBackground(new java.awt.Color(0, 102, 102));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("LOGIN");

        usernameLB1.setBackground(new java.awt.Color(102, 102, 102));
        usernameLB1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLB1.setText("Username :");

        usernameTB1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameTB1.setForeground(new java.awt.Color(102, 102, 102));

        passwordLB1.setBackground(new java.awt.Color(102, 102, 102));
        passwordLB1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLB1.setText("Password :");

        errorLB1.setForeground(new java.awt.Color(255, 51, 51));
        errorLB1.setText("Invalid Credentails ...");

        LoginButton1.setBackground(new java.awt.Color(0, 102, 102));
        LoginButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginButton1.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton1.setText("Login");
        LoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordLB1)
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errorLB1)
                                    .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(usernameLB1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel3)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTB1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLB1))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLB1)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(errorLB1)
                .addGap(32, 32, 32)
                .addComponent(LoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButton1ActionPerformed
        // TODO add your handling code here:
        String userName = this.usernameTB1.getText();
        String password = this.jPasswordField2.getText();

        if (validateCredentials(userName, password)) {
            if (business != null) {
                UserAccountDirectory uadirectory = business.getUserAccountDirectory();
                UserAccount ua = uadirectory.AuthenticateUser(userName, password);
                if (ua != null) {
                    String userRole = ua.getRole();
                    if (userRole.equalsIgnoreCase("sales")) {
                        SalesDashboardPanel saleDash
                                = new SalesDashboardPanel(business, ua, ContentPanel);
                        ContentPanel.add("SaleDash", saleDash);
                        CardLayout layout = (CardLayout) ContentPanel.getLayout();
                        layout.next(ContentPanel);
                    } else if (userRole.equalsIgnoreCase("Marketing")) {
                        MarketDashboardPanel markDash
                                = new MarketDashboardPanel(business, ua, ContentPanel);
                        ContentPanel.add("markDash", markDash);
                        CardLayout layout = (CardLayout) ContentPanel.getLayout();
                        layout.next(ContentPanel);
                    } else if (userRole.equalsIgnoreCase("Admin")) {
                        AdminDashboardPanel adminPanel
                                = new AdminDashboardPanel(business, ua, ContentPanel);
                        ContentPanel.add("AdminDash", adminPanel);
                        CardLayout layout = (CardLayout) ContentPanel.getLayout();
                        layout.next(ContentPanel);
                    }

                    this.loginButton.setVisible(false);
                    this.logoutButton.setVisible(true);
                    this.welcomLB.setVisible(true);
                    this.welcomLB.setText("Welcome :" + ua.getPersonId());
                } else {
                    this.errorLB1.setVisible(true);
                    this.errorLB1.setText("");
                    this.errorLB1.setText("Invalid User Credentials !");
                }
            }
        }
    }//GEN-LAST:event_LoginButton1ActionPerformed

    private boolean validateCredentials(String userName, String password) {
        if (userName.trim().isEmpty()) {
            this.errorLB1.setVisible(true);
            this.errorLB1.setText("");
            this.errorLB1.setText("Please enter Username !");
            return false;
        }
        if (password.trim().isEmpty()) {
            this.errorLB1.setVisible(true);
            this.errorLB1.setText("");
            this.errorLB1.setText("Please enter Password !");
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LoginButton1;
    private javax.swing.JLabel errorLB;
    private javax.swing.JLabel errorLB1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel passwordLB;
    private javax.swing.JLabel passwordLB1;
    private javax.swing.JLabel usernameLB;
    private javax.swing.JLabel usernameLB1;
    private javax.swing.JTextField usernameTB;
    private javax.swing.JTextField usernameTB1;
    // End of variables declaration//GEN-END:variables
}
