/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elearning.ui.issuer;

import elearning.models.ProfessorDataModel;
import elearning.models.StudentDataModel;
import elearning.models.UserDefaultDataModel;
import elearning.models.UserModel;
import elearning.models.UserSignUpModel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author harsh
 */
public class IssuerDashboardPanel extends javax.swing.JPanel {

    JPanel appContainerPanel;
    UserSignUpModel userSignUpObj;
    UserModel userObj;
    UserDefaultDataModel userDefaultDataObj;
    ProfessorDataModel professorDataObj;
    StudentDataModel studentDataObj;

    /**
     * Creates new form EmployerDashboardPanel
     *
     * @param appContainerPanel
     * @param userSignUpObj
     * @param userObj
     * @param userDefaultDataObj
     * @param professorDataObj
     * @param studentDataObj
     */
    public IssuerDashboardPanel(JPanel appContainerPanel,
            UserSignUpModel userSignUpObj, UserModel userObj,
            UserDefaultDataModel userDefaultDataObj,
            ProfessorDataModel professorDataObj,
            StudentDataModel studentDataObj) {
        initComponents();

        this.appContainerPanel = appContainerPanel;
        this.userSignUpObj = userSignUpObj;
        this.userObj = userObj;
        this.userDefaultDataObj = userDefaultDataObj;
        this.professorDataObj = professorDataObj;
        this.studentDataObj = studentDataObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        IssuerMenuPanel = new javax.swing.JPanel();
        ProfileButton = new javax.swing.JButton();
        StudentsButton = new javax.swing.JButton();
        ProfessorsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        IssuerContentPanel = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        IssuerMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        IssuerMenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProfileButton.setBackground(new java.awt.Color(51, 153, 255));
        ProfileButton.setText("Profile");
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        StudentsButton.setBackground(new java.awt.Color(51, 153, 255));
        StudentsButton.setText("Students List");
        StudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsButtonActionPerformed(evt);
            }
        });

        ProfessorsButton.setBackground(new java.awt.Color(51, 153, 255));
        ProfessorsButton.setText("Professors List");
        ProfessorsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfessorsButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Issue Certificate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IssuerMenuPanelLayout = new javax.swing.GroupLayout(IssuerMenuPanel);
        IssuerMenuPanel.setLayout(IssuerMenuPanelLayout);
        IssuerMenuPanelLayout.setHorizontalGroup(
            IssuerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssuerMenuPanelLayout.createSequentialGroup()
                .addContainerGap(577, Short.MAX_VALUE)
                .addComponent(ProfileButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IssuerMenuPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProfessorsButton)
                .addGap(90, 90, 90)
                .addComponent(StudentsButton)
                .addGap(82, 82, 82))
        );
        IssuerMenuPanelLayout.setVerticalGroup(
            IssuerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssuerMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(IssuerMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentsButton)
                    .addComponent(ProfessorsButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(IssuerMenuPanel);

        IssuerContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        IssuerContentPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(IssuerContentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        // TODO add your handling code here:
        IssuerProfileResetPanel profileReset = new IssuerProfileResetPanel(
                appContainerPanel, IssuerContentPanel, userObj, userSignUpObj);
        IssuerContentPanel.add("IssuerProfile", profileReset);
        CardLayout layout = (CardLayout) IssuerContentPanel.getLayout();
        layout.next(IssuerContentPanel);
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void ProfessorsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfessorsButtonActionPerformed
        // TODO add your handling code here:
        IssuerRegisteredProfessorsPanel profPanel = new IssuerRegisteredProfessorsPanel(
                IssuerContentPanel, userSignUpObj);
        IssuerContentPanel.add("IssuerProfessors", profPanel);
        CardLayout layout = (CardLayout) IssuerContentPanel.getLayout();
        layout.next(IssuerContentPanel);

    }//GEN-LAST:event_ProfessorsButtonActionPerformed

    private void StudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsButtonActionPerformed
        // TODO add your handling code here:
        IssuerRegisteredStudentsPanel stuPanel = new IssuerRegisteredStudentsPanel(
                IssuerContentPanel, userSignUpObj);
        IssuerContentPanel.add("IssuerStudents", stuPanel);
        CardLayout layout = (CardLayout) IssuerContentPanel.getLayout();
        layout.next(IssuerContentPanel);
    }//GEN-LAST:event_StudentsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        IssuerCertificateIssuePanel issueCert = new IssuerCertificateIssuePanel(
                IssuerContentPanel, userObj, userSignUpObj, studentDataObj);
        IssuerContentPanel.add("IssuerCerts", issueCert);
        CardLayout layout = (CardLayout) IssuerContentPanel.getLayout();
        layout.next(IssuerContentPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IssuerContentPanel;
    private javax.swing.JPanel IssuerMenuPanel;
    private javax.swing.JButton ProfessorsButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton StudentsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
